### ISSUE TITLE
"Cannot parse server response" with HTTP 204

### ISSUE THREAD

**Issue by shaneneuerburg** [bustoutsolutions/siesta#11]
If I understand the Siesta documentation correctly, when doing a POST request, it should be acceptable to receive HTTP 204 with no body. When I attempt that, I get the following:

```
[Siesta:Network] POST http://localhost/account
[Siesta:Network] 204 ← POST http://localhost/account
[Siesta:NetworkDetails] Raw response headers: [Content-Length: 0, Access-Control-Allow-Origin: *, Vary: Accept, Content-Type: application/json; charset=utf-8, Content-Language: en-US, Access-Control-Allow-Headers: *, Connection: Keep-Alive, Access-Control-Max-Age: 1000, Expires: 0, Server: Apache/2.4.7 …
[Siesta:NetworkDetails] Raw response body: 0 bytes
[Siesta:ResponseProcessing] ResponseContentTransformer<NSData, NSJSONConvertible>(processor: (Function), skipWhenEntityMatchesOutputType: true, transformErrors: true) matches content type "application/json; charset=utf-8"
[Siesta:ResponseProcessing] ResponseContentTransformer<NSData, NSJSONConvertible>(processor: (Function), skipWhenEntityMatchesOutputType: true, transformErrors: true) → Error(userMessage: "Cannot parse server response", httpStatusCode: nil, entity: nil, cause: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.}), timestamp: 469262441.985034)
[Siesta:NetworkDetails] Response after transformer pipeline:  (new data) 
   Failure
     userMessage:    "Cannot parse server response"
     cause:          Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.}
```

Is there something I need to do in order to get this to work?

**Comment by pcantrell** [comment]
This should be fixed in the next beta release.

If you’re brave and foolhardy, try `master` and see if it’s fixed for you already.

**Comment by pcantrell** [comment]
Wait, apologies, I mistook this for another bug. I should have looked at your log more carefully before answering.

It looks like your server is sending `Content-Type: application/json` even though the response is empty. That’s causing Siesta to attempt to parse the response as JSON, which gives the “no value” error you’re seeing.

A 204 should not give a content-type header, since there is no content. Is that something you have control over?

**Comment by shaneneuerburg** [comment]
The library used for the scaffolding of the API is Restler (PHP), which apparently doesn't abide by that rule. I'll post an issue with them and see if I can override that for now.

**Comment by pcantrell** [comment]
If they're unable to change it, feel free to reopen this issue, and we'll either decide to make Siesta handle it as a special case or get you a configuration workaround.

**Comment by pcantrell** [comment]
Seeing that you’ve only got a workaround from the Restler side, I’ll give you a Siesta-side workaround to choose from as well.

You can make a response transformer that assigns a made-up content-type to empty responses to suppress further processing:

    struct ChangeEmptyResponseContentType: ResponseTransformer
        {
        func process(response: Siesta.Response) -> Siesta.Response
            {
            switch(response)
                {
                case .Success(var entity):
                    if let data = entity.content as? NSData where data.length == 0
                        { entity = Entity(content: NSData(), contentType: "unknown/empty") }
                    return .Success(entity)
                
                case .Failure:
                    return response
                }
            }
        }

…and then, when configuring your service, make it the first transformer in the pipeline:

    configure
        {
        $0.config.responseTransformers.add(
            ChangeEmptyResponseContentType(),
            first: true)
        }

That’s just a hack, but it does give you another option if the Restler patch doesn’t suit.

**Comment by shaneneuerburg** [comment]
Great, thank you!

**Comment by joaomvfsantos** [comment]
@pcantrell I'm having the same issue, on my side I can't do anything about the server so I was looking to do something like the work around you suggested. Seems the syntax is for a deprecated version of Siesta. I'm adding the ChangeEmptyResponseContentType transformer like the below, but still have Siesta returning me the "Cannot parse server response" error.

```
configure(configurer: { (configuration) in
     configuration.pipeline[.rawData].add(ChangeEmptyResponseContentType())
     configuration.pipeline[.rawData].cacheUsing(PersistentCache<Data>())
     configuration.headers["Authorization"] = self.headers["Authorization"]
})
```

PersistentCache is my implementation of EntityCache I'm using and the Authorization header, well, it's just an Authorization header. Any ideas?

Thank you!
