### ISSUE TITLE
xcode 8 Swift 3 cocoapods error

### ISSUE THREAD

**Issue by Reedyuk** [bustoutsolutions/siesta#110]
Hi Paul,
I'm half way through updating my current project to Swift 3.0 and I have updated the pod dependancy for Siesta.

`pod 'Siesta' , '1.0-beta.10'`

But when I try to compile, I'm getting a load of swift compiler errors. Any thoughts? See screenshot attached.

![screen shot 2016-09-14 at 16 59 21](https://cloud.githubusercontent.com/assets/3853006/18519661/a757082c-7a9c-11e6-9559-9872923286a9.png)

**Comment by pcantrell** [comment]
`1.0-beta.10` is a Swift 2 release.

There is no Swift 3 release yet, because the example code in the docs has to be updated & I need to write up some migration instructions. Use `master` until there’s an official release.

**Comment by pcantrell** [comment]
Also, I’d like to hear some smoke test success from users before I declare a Swift 3 release, so please let me know about how it works for you — and if there are migration difficulties I should include in the docs.

**Comment by Reedyuk** [comment]
ok thanks, 
Any chance you could either branch a 'Swift-3.0' or even add to the readme that you must point to master, as i easily overlooked this.
Yes, i will let you know how it goes.

**Comment by pcantrell** [comment]
There has been a `swift3` branch for some weeks, but it merged to master when Swift 3 went GM per the [release plan](http://bustoutsolutions.github.io/siesta/guide/faq/#roadmap-1-0).

I’m leaving this issue open, so hopefully others will find it if they’re confused!

**Comment by awclives** [comment]
Hi,

I am one of the confused.

I am using cocoapods, XCode 8, and swift 3.  

What should I have in my podfile?
pod 'Siesta', '>=1.0-rc.0'
or 
pod 'Siesta' , :git => 'https://github.com/bustoutsolutions/siesta.git', :branch => 'master'
?

Thanks.

**Comment by awclives** [comment]
The former looks correct; however, the following is not compiling:

`	service.configureTransformer("/highlight-feed/simple/") {
			if let dic = $0.content.dictionaryObject, let ret: HighlightFeed = try? Unbox(dic) {
				return ret
			}
			return nil
		}
`

I get the error "Type COnfigurationPatternConvertible does not conform to protocol ExpressibleByStringLiteral".

**Comment by pcantrell** [comment]
>What should I have in my podfile?
> `pod 'Siesta', '>=1.0-rc.0'`
>or 
>`pod 'Siesta' , :git => 'https://github.com/bustoutsolutions/siesta.git', :branch => 'master'`

Both should work. As Jordan pointed out in another thread, `rc.0` incorrectly says that Siesta requires iOS 9, but that’s the only issue I know of at the moment.

Your compile error is because you aren’t giving Swift enough information to infer the input type of your transformer. What is `.dictionaryObject` and what type is it supposed to come from? How would Swift know that from context? (The error message about “ExpressibleByStringLiteral” is completely misleading. It’s a terrible message.)

The way to debug a type inference problem like this is to switch from `$0` to an explicitly declared `entity` input:

```
service.configureTransformer("/highlight-feed/simple/") {
    (entity: Entity<WhateverInputTypeDictionaryObjectIsSupposedToComeFrom>) -> HighlightFeed? in
    if let dic = entity.content.dictionaryObject,
       let ret: HighlightFeed = try? Unbox(dic) {
        return ret
    }
    return nil
}
```

In any case, I don’t think it’s a Swift 3 compatibility issue — but please open a new issue if you determine that it is.

**Comment by awclives** [comment]
Thank you, sir.  Can't test my full project yet, but your suggestion seems to be working.

**Comment by pcantrell** [comment]
The official Swift 3 release is out and it looks like it’s working for people, so I’m closing this.
