### ISSUE TITLE
Can not install pods with iOS 8 deployment target

### ISSUE THREAD

**Issue by roma86** [bustoutsolutions/siesta#114]
Hello, thank you for your work.

When i try to `pod install` or `pod update` for such a Podfile:

```
platform :ios, '8.0'

target SomeTarget do
   pod 'Siesta', '1.0-rc.0'
end

```

I have error 
> [!] Unable to satisfy the following requirements:
> - `Siesta (= 1.0-rc.0)` required by `Podfile`
> Specs satisfying the `Siesta (= 1.0-rc.0)` dependency were found, but they required a higher minimum deployment target.

This is happen only for current library. 

My other dependencies:

```
   pod 'AlamofireImage'
   pod 'SVProgressHUD'
   pod 'GRDB.swift'
   pod 'SHSPhoneComponent'
   pod 'SwiftDate'
   pod 'SwiftyJSON'
   pod 'Device'
   pod 'JTAppleCalendar'
   pod 'GlyuckDataGrid'
```

does not produce such error.

-------

I have tried to use `pod _1.1.0.rc.2_ update` with same result.

My development environment is
xcode 8
mac os 10.11.6
cocoapods 1.0.1 adn 1.1.0.rc.2
project originally wrote with swift 2.1 and now i trying to migrate to swift 3.

**Comment by pcantrell** [comment]
The `rc.0` podspec erroneously requires 9.0 even though Siesta itself works with 8.0 (see #112). This is fixed on master:

    pod 'Siesta', git: 'https://github.com/bustoutsolutions/siesta.git', branch: 'master'

…and the fix will go out in the next official release.
