### ISSUE TITLE
Getting a resources URL from any thread

### ISSUE THREAD

**Issue by jordanpwood** [bustoutsolutions/siesta#124]
I know that Siesta has some smarts when it comes to formatting URL paths.  I'm wondering if there is a good way for me to leverage that to be able to construct a URL (just to return it) to a resource from any thread.  I can do such a thing in my own code, but if its available somewhere under the hood it'd be nice to use it, and be confident that it is the URL that is _actually_ used in Siesta. I can't use `service.resource(relativePathString).url.absoluteString` because that can only be called from the main thread.  

Any suggestions you have would be appreciated!

**Comment by pcantrell** [comment]
Siesta’s only real magic is knowing which `URL` and `URLComponents` methods to use — it’s not always obvious — and wrapping them in a less clunky API. The actual escaping is all in Foundation.

The relative path logic you’re talking about all comes from `URL(string: relativeURL, relativeTo: parentURL)`, and that you can certainly call from any thread. All of the path resolving code is [here](https://github.com/bustoutsolutions/siesta/blob/master/Source/Siesta/Resource/ResourceNavigation.swift#L36), [here](https://github.com/bustoutsolutions/siesta/blob/master/Source/Siesta/Resource/ResourceNavigation.swift#L94-L96), and [here](https://github.com/bustoutsolutions/siesta/blob/master/Source/Siesta/Support/NSURL%2BSiesta.swift#L34-L67). (The params that are the messiest to deal with.) Hope that helps!

---

If you find yourself wanting to resolve URLs throughout your code, then beside the threading issue, there’s the problem of having many bits of code tightly coupled to your API’s URL layout. I don’t know if this is relevant to your situation, Jordan, but I’ll mention an approach that can work nicely in case it’s useful to either you or to others:

1. Make a domain-specific struct that allows navigation within the _logical_ structure of your problem domain, and doesn’t know anything about URLs.
2. Let your Siesta API wrapper map from that struct to Resources, hiding all URL structure from the rest of the app.

For example:

    enum Foot: String {
        case left
        case right

        var other: Foot {
            switch(self) {
                case left:  return right
                case right: return left
            }
        }
    }

    struct ShoeDescriptor {
        var model: String
        var foot: Foot

        // Here we're effectively navigating from one resource to another,
        // but doing no URL operations — and nothing that touches
        // Resource, so it can run on any thread. Note that we could
        // do this with resource.relative(…), but this way crisply
        // distinguishes changing foot from changing shoe model.

        var counterpart: Shoe {
            return Shoe(model: model, foot: foot.other)
        }
    }

…and then:

    class MyAPI {
        ...
        func shoe(for descriptor: ShoeDescriptor) -> Resource {

            // Actual URL structure fully encapsulted in MyAPI

            return service
                .resource("/shoes")
                .child(descriptor.model)
                .child(descriptor.rawValue)
        }
        ...
    }

The GithubBrowser example uses `Repository` this way.

**Comment by jordanpwood** [comment]
Sorry, I was just doing something stupid in my tests. 

I agree, URLs shouldn't be used to identify resources in the app, I just wanted them for testing and reporting uses.

**Comment by pcantrell** [comment]
Fair enough, and no apologies needed! I always overexplain for these sorts of best practice questions in the hopes that it will be useful in the future to others who are searching for answers. (Speaking of which, you might have useful contributions to [this discussion of mocking with Siesta](http://stackoverflow.com/questions/39827137/how-can-i-mock-resource-responses/39843504).)

OK to close this?
