### ISSUE TITLE
Request: NetworkActivityIndicator

### ISSUE THREAD

**Issue by Reedyuk** [bustoutsolutions/siesta#129]
Hi,
In my app, there is some cases where I would like to show the status bar NetworkActivityIndicator when siesta is performing a network request.
At the moment, i show the indicator when i run loadIfNeeded BUT obviously this works fine when the cache is clear, but not when the cache isn't. 
I hide the network activity indicator on the callback resourceChanged, but this is not called when the cache is being used. 
So would it be possible to have a Siesta property to automatically show/hide the indicator when network activity is being performed?

**Comment by pcantrell** [comment]
Siesta already make this reasonably easy to build yourself. First write a little helper to track multiple simultaneous requests, because iOS’s activity indicator won’t do that for you:

```swift
private var requestsInProgress = 0 {
  didSet {
    UIApplication.shared.isNetworkActivityIndicatorVisible =
        requestsInProgress > 0
  }
}

private func requestStarted() {
    requestsInProgress += 1
}

private func requestCompleted() {
    requestsInProgress -= 1
}
```

Then you can make an entire `Service` (or multiple ones!) update the activity indicator automatically for all requests:

```swift
extension Service {
    func showRequestsWithNetworkActivityIndicator() {
        configure {
            $0.decorateRequests {
                res, req in
                
                requestStarted()
                req.onCompletion { _ in requestCompleted() }
                
                return req
            }
        }
    }
}
```
```swift
service.showRequestsWithNetworkActivityIndicator()
```

I think that should do the trick for you? Feel free to reopen this if it doesn’t, and there’s a missing feature here!

**Comment by Reedyuk** [comment]
Thanks Paul, i will implement this, but because the loading indicator is already there by default(just not used by siesta), i think that this should be a property on the service layer. 
I can totally understand if i was talking about a 3rd party library, but because its apart of ios(so to say), it feels like this should just be a boolean property to enable disable in siesta.

**Comment by Reedyuk** [comment]
Hi Paul,
https://github.com/bustoutsolutions/siesta/pull/132
I have created a pull request with my changes.

**Comment by Alex293** [comment]
This works well but it would be better if it was handled by Siesta as Reedyuk requested. The main reason is that its easy to use with the code above but as RemoteImageView use it's own service I have to configure it too and so on for every small service designed for special cases.

**Comment by Reedyuk** [comment]
@Alex293 - you should be keeping an instance of your service object, so you should only need to do it once(depending on how many service object you keep).
Checkout my PR, i added to the GitHub example to show the indicator. One line and it does the rest.

**Comment by Alex293** [comment]
The problem is that sometimes you have multiple service that you don't own like in RemoteImageView that create it's own service

**Comment by pcantrell** [comment]
@Reedyuk: Thanks for the PR! A good addition. I’ll post some comments over there.

@Alex293 wrote:

> The problem is that sometimes you have multiple service that you don't own like in RemoteImageView that create it's own service

No problem:

```swift
RemoteImageView.defaultImageService.showRequestsWithNetworkActivityIndicator()
```

…or for a particular one, if it doesn’t use the default:

```swift
myRemoteImageView.imageService.showRequestsWithNetworkActivityIndicator()
```
