### ISSUE TITLE
Ability to integrate just using source

### ISSUE THREAD

**Issue by jonsteinmetz** [bustoutsolutions/siesta#14]
I settled on using Carthage but I would rather use git submodules and include the source myself. Any thoughts on supporting this workflow? When I last tried that there was one place that did an `import Siesta` which is not compatible with including source from what I can tell.

**Comment by pcantrell** [comment]
That file with the “import Siesta” is a problem child. It’s optional, only necessary if you want to use Alamofire; you can just exclude it. It was part of the main framework until it became clear that optional dependencies really aren’t. Before the next beta, I’m going to either (most likely) move it into a different source folder, or even a different project. In face, I think I’ll just do that for you right now….

**Comment by pcantrell** [comment]
Moved it. Should now build cleanly from source if you only include `Source/`.

**Comment by jonsteinmetz** [comment]
Actually there is a spot in Progress.swift that refers to `Siesta.now()`. Changing this to `now()` and changing the variable name `now` to `timeNow` seems to fix the issue. If this seems reasonable perhaps I should try out my first pull request.

**Comment by pcantrell** [comment]
I assumed the issue with `import Siesta` was the module not being able to import itself, but it sounds like what’s happening is that you’re not building Siesta as a module _at all_.

I don't recommend doing that. The project has a number of types that make sense when namespaced to a module, but that you probably don’t want just dropped into your global namespace (e.g. it’s one thing having `Siesta.Error`, but it’s another having something just called `Error`).

Even if you’re including the source as a git submodule, I’d strongly recommend still building Siesta as its own Swift module. Whether the right way to do that is as a separate target in the same xcproj or as an xcworkspace with the Siesta project nested in it, I can’t say.

**Comment by jonsteinmetz** [comment]
Makes sense. Thanks.

**Comment by pcantrell** [comment]
You bet.

The moment for your first PR will come yet, I have no doubt!
