### ISSUE TITLE
iOS 8 compatibility

### ISSUE THREAD

**Issue by pavelsmelovsky** [bustoutsolutions/siesta#147]
Please reset the minimum iOS SDK to iOS 8. And set the minimum Alamofire dependency to version 4.1.

**Comment by pcantrell** [comment]
It is already set to iOS 8 in both the embedded xcodeproj (used by Carthage) and the podspec. The forthcoming 1.0.0 uses AF 4.1 for its own internal testing, and Siesta does not impose any Alamofire version requirements downstream anyway.

In other words, this should already work. Can you please describe the problem you're seeing? What Siesta version are you using?

**Comment by pavelsmelovsky** [comment]
I'm trying to add Siesta pod like this:

> pod 'Siesta/Alamofire', '>=1.0.0'

but cocoapod return an error:

> [!] Unable to satisfy the following requirements:
> 
> - `Siesta/Alamofire (>= 1.0.0)` required by `Podfile`
> 
> None of your spec sources contain a spec satisfying the dependency: `Siesta/Alamofire (>= 1.0.0)`.
> 
> You have either:
>  * out-of-date source repos which you can update with `pod repo update`.
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.

I can install only 1.0-rc.3 version that requires iOS 9+

**Comment by pcantrell** [comment]
> [!] Unable to satisfy the following requirements:

You probably just beat the 1.0.0 release propagating to CocoaPods. Give it 15 minutes and try again.

> I can install only 1.0-rc.3 version that requires iOS 9+

1.0-rc.3 also [supports iOS 8](https://github.com/bustoutsolutions/siesta/blob/1.0-rc.3/Siesta.podspec#L69).

**Comment by pavelsmelovsky** [comment]
Ok, i'm trying later.

> 1.0-rc.3 also supports iOS 8.

>   s.subspec "Alamofire" do |s|
>     s.source_files = "Extensions/Alamofire/**/*"
>     s.dependency "Siesta/Core"
>     s.dependency "Alamofire", "> 4"
>     s.ios.deployment_target = "9.0"
> end

In our project we use Siesta/Alamofire, and it require iOS 9. But it not a problem, for current time I fix it manualy

**Comment by pavelsmelovsky** [comment]
Topic can be closed.
CocoaPods updated Siesta pod.

Thanks!

**Comment by pavelsmelovsky** [comment]
Paul, I see another problem with current version 1.0.0:
The deployment target of Siesta pod is 9.0 (I'm installing Siesta/Alamofire), cocoapods show me error:

> Specs satisfying the `Siesta/Alamofire (>= 1.0.0)` dependency were found, but they required a higher minimum deployment target.

Fix this please.
Thanks!

**Comment by pcantrell** [comment]
I believe that’s a limitation of Alamofire, not Siesta. I’m not sure there even is a release of Alamofire that supports both Swift 3 and iOS 8.

**Comment by pavelsmelovsky** [comment]
Alamofire requirements (since 4.1.0):

-     iOS 8.0+ / macOS 10.10+ / tvOS 9.0+ / watchOS 2.0+
-     Xcode 8.1+
-     Swift 3.0+

Only two pods in my list asked for iOS 9 - Siesta (I don't know why) and AlamofireImage.
I manualy change deployment target to 8.0 and remove @available(iOS 9.0, *) in Siesta/Alamofire/Networking-Alamofire.swift and all working correct

**Comment by pcantrell** [comment]
Ah, IIRC at one point AF 4 did require iOS 9, and I had to update the subspec to match. Either they fixed that or I misremembered. I’ll fix it in 1.0.1.
