### ISSUE TITLE
How to handle Json null

### ISSUE THREAD

**Issue by Alex293** [bustoutsolutions/siesta#150]
Hi,

I have an issue with a server responding a null JSON on a particular successfull request.

As the answer is null Siesta return me an error : JSONResponseIsNotDictionaryOrArray(actualType: NSNull). The thing is this is a successful request but Siesta consider it as an error. (null is considered as a valid JSON according to the RFC so I can't claim too the provider to change this)

Can you give me clue on how to avoid this situation ?

**Comment by pcantrell** [comment]
This is an unfortunate but intentional design compromise for Siesta’s `JSONResponseTransformer`. It may deserve some rethinking.

For now, try adding this to your app to signal that you accept `NSNull` as JSON content:

```swift
extension NSNull: JSONConvertible { }
```

**Comment by Alex293** [comment]
Awesome at least I can go on ! Closing this for now, if I have issue with this fix I'll open it again. If you think of some way to apply it only on one particular resource or request to be sure there is no side effect I'd be interested.
