### ISSUE TITLE
Typed request

### ISSUE THREAD

**Issue by piv199** [bustoutsolutions/siesta#151]
Hi, I'm new to Siesta.

I have api service and a bunch of methods in it. Each method returns `Request`, so I could further chain them or start later, what I want... Then in some place I have:
```
api.myMethod().onSuccess { entity in
   //here entity.content is of type Any and I must downcast, but it's a bad choice to do it here 
   //how could I set type of content in response while in `myMethod()` returning a request
   // P.s. I have some transformers configured in my api service, so response by `myMethod()` request is transformed to some model type
}.onFailure { error in
   print(error)
}
```

**Comment by pcantrell** [comment]
See “[Why doesn’t Siesta provide a typesafe Resource<T>?](http://bustoutsolutions.github.io/siesta/guide/faq/#why-doesnt-siesta-provide-a-typesafe-resourcet)” in the FAQ.

In the meantime:

```swift
api.myMethod().onSuccess { entity in
    let user: MyUserModel? = entity.typedContent()
}
```

(Note also that to get the full benefit of Siesta, you don’t want to be attaching `onSuccess()` to individual requests, but rather observing the resource.)

**Comment by piv199** [comment]
@pcantrell, okay but I am a bit misunderstood with siesta

What the difference between Request and Resource?

I have AuthService with signIn, signUp requests, so I could call them when pressing on button and listen whether response is succeeded or failed, don't I?

I have some TasksResource: Resource and I want to observe tasks changes? Or when I need to use a Resource.


P.S.

```
api.myMethod().onSuccess { entity in
    let user: MyUserModel? = entity.typedContent()
}
```

I do not like this case, because it could be used lots across the program and will lead to potential duplication and requires changes in many places...

**Comment by piv199** [comment]
@pcantrell Also I have doubts if I have resource `"news"` and I want to call method `"all"` -> I do `newsResource.child("all").start()`, but `"news"` resource won't get any updates :(

**Comment by piv199** [comment]
@pcantrell also why Resource marked as final class?

**Comment by Alex293** [comment]
Each URL give a different resource so I you have new/all and news/1 you have two resources. Now if you look at the quick start in the request section for post etc there is a way that you use the result of a request to update an existing resource. I you want to perform a request without cache you should use resource.request(.get) instead resource

**Comment by pcantrell** [comment]
> What the difference between Request and Resource?

Read the [User Guide](http://bustoutsolutions.github.io/siesta/guide/), especially the first 4 pages (Resources, Resource State, Observers, and Requests). This will answer a lot of your questions.

See also the [API docs for Request](http://bustoutsolutions.github.io/siesta/api/Protocols/Request.html) for info on how it differs from Resource.

> I do not like this case, because it could be used lots across the program and will lead to potential duplication and requires changes in many places

It doesn’t play out so badly in practice, especially if you let Swift’s type inference guide `typedContent()` for you. See the code in the example project.
