### ISSUE TITLE
Try again can't be translated

### ISSUE THREAD

**Issue by Alex293** [bustoutsolutions/siesta#155]
Hi,

Working on translating my app I found that there is no way to easily change the title of the Try again button in the ResourceStatusOverlay. There is an option for the title so it may be a good idea to do the same for the button ?

**Comment by pcantrell** [comment]
I’d welcome a PR for this. I’m not sure whether it’s preferable to use [base internationalization](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/InternationalizingYourUserInterface/InternationalizingYourUserInterface.html#//apple_ref/doc/uid/10000171i-CH3-SW2) and have strings files for the storyboard, or just set a localized button title in code.

Opinions on that?

**Comment by Alex293** [comment]
I feel like ResourceStatusOverlay is supposed to be used as a drop-in composant and should not not be subclassed or customised a lot. So it would be very convenient that Siesta handle internationalisation but It would require then a lot's of work to keep it compatible with a large number of langages. On the other hand providing an optional title property wouldn't be a great effort and would give the user a more complete customisation.

**Comment by pcantrell** [comment]
I’d be fine with exposing a `retryButton` property for the button itself, much like the current `errorHeadline`. Would that suit your needs?

**Comment by Alex293** [comment]
Sure

**Comment by pcantrell** [comment]
Go ahead and submit a pull request for this. I’d be happy to accept it!
