### ISSUE TITLE
List of children

### ISSUE THREAD

**Issue by Alex293** [bustoutsolutions/siesta#156]
Hi,

When I do a post on a certain request I'd like to refresh all children of a particular other resource.
What could be a good strategy to achieve this ?

Example : I get items for a map based on map edges : getItemResource?ne=coord&sw=coord
How to do a getItemResource.load that affects all the children ? Something like invalidateChildren

**Comment by pcantrell** [comment]
Siesta intentionally does not track any relationships between resources. A future major revision might use a more GraphQL-like internal structure for the cache, but that’s a massive undertaking next to Siesta’s simple resource-based approach, so not on the table for now.

As Siesta exists, it’s up to you to establish relationships between resources. One strategy would be for anything that observers a child to also observe its parent and trigger a refresh if new data comes in, e.g.:

```swift
childResource.addObserver(self)
parentResource.addObserver(owner: self) {
  if case .newData = $1 {
    childResource.invalidate()
    // Delayed refresh prevents redundant load if multiple
    // children trigger a refresh on the same parent
    DispatchQueue.main.async {
      childResource.loadIfNeeded()
    }
  }
}
```

**Comment by Alex293** [comment]
This is what I did but it's not very convenient to keep a pointer to child and parent a t the same time. For now it's working with this so I close this issue but add here any informations on a better way to do it.
