### ISSUE TITLE
Intercept Log

### ISSUE THREAD

**Issue by Reedyuk** [bustoutsolutions/siesta#157]
Hi Paul,
Just wondering if its possible to intercept the log from siesta. 
I want to use:
[https://github.com/Cosmo/TinyConsole](https://github.com/Cosmo/TinyConsole) 
in my debug builds and i want to see the Siesta log output there too. 

Thanks
Andrew.

**Comment by pcantrell** [comment]
Yup, [Siesta has that](http://bustoutsolutions.github.io/siesta/guide/logging/#custom-log-action).

(Feel free to reopen this if that’s not what you’re looking for.)
