### ISSUE TITLE
Multiple transformers for same wildcard

### ISSUE THREAD

**Issue by Reedyuk** [bustoutsolutions/siesta#159]
Hi Paul,
I have a problem at the moment, my api is structured like this:

> Get Pots -> /service/users/USER_ID/pots -> Returns Array of pots
> Post to create pots ->  /service/users/USER_ID/pots -> Returns Dictionary of pot detail

The issue with this is that when i set my transformers, they are using the same url, so when i go to create a pot, then it tries to invoke the get pots transformer instead of the create pot transformer and fails. 

I hope i made that clear enough? So two possible solutions are:

1. Siesta tries all the transformers, instead of failing on first match
2. Siesta offers transformer mapping via request type e.g. .post or .get

Thanks
Andrew.

**Comment by pcantrell** [comment]
Siesta lets you configure a whole pipeline for each resource and request method. Each chunk of configuration can add, insert, and replace previously configured transformers in the pipeline.

I added some example to the [pipeline chapter of the user guide](http://bustoutsolutions.github.io/siesta/guide/pipeline/#model-mapping) that demonstrate this. Look for “Note that this method replaces the transformer(s) at the stage you specify” for the relevant text.

**Comment by Reedyuk** [comment]
Amazing! Thanks Paul, exactly what i needed.
So i implemented it so:

```
NetworkRequestAdapter.webService.configureTransformer(Urls.CreatePotService.createPotWildcard, requestMethods: [.post]) {
            Pot.createPot(json: $0.content)
        }
        NetworkRequestAdapter.webService.configureTransformer(Urls.PortfolioService.getPotsWildcard, requestMethods: [.get]) {
         Pot.createPots(json: $0.content)
        }
```
