### ISSUE TITLE
No such module 'Siesta'

### ISSUE THREAD

**Issue by lifeisfoo** [bustoutsolutions/siesta#16]
I've just installed Siesta (1.0-beta.4) using cocoapods, but when I try to import it with `import Siesta` inside a swift file I receive this error.

This is my Podfile:

    platform :ios, '8.0'
    use_frameworks!
    pod 'Siesta', '~>1.0-beta.4'

I'm using xcode 7.2.

Thank you.

**Comment by lifeisfoo** [comment]
I've used the wrong `.xcworkspace`file to open the xcode project.
The correct was in the the project root.

**Comment by pcantrell** [comment]
Glad you fixed it! Let us know how Siesta goes for you once you’ve had a chance to experiment.

**Comment by lifeisfoo** [comment]
I'm trying to use it in a new production app :smiling_imp:

**Comment by pcantrell** [comment]
Great! Be sure to tweet @siestaframework about the app when it's live!

**Comment by lifeisfoo** [comment]
Sure. Thank you for your work.

P.s.
I've added this QA to stackoverflow to help as many people as possible: 
http://stackoverflow.com/questions/34185372/cocoapods-no-such-module-siesta/34185373
