### ISSUE TITLE
Obj-C examples

### ISSUE THREAD

**Issue by guidedways** [bustoutsolutions/siesta#161]
I know this should work fine from Obj-C, however for someone who doesn't yet know Swift (yikes), it would actually help if the examples / documentation had equivalent Obj-C code.

**Comment by pcantrell** [comment]
Keeping doc-wide Obj-C examples up to date is a bit more than this project can take on. Also, many — perhaps most — of the examples are for sticky things that require examples are configuration-related, and thus Swift-only.

There are a few example snippets on the [Obj-C page of the user guide](http://bustoutsolutions.github.io/siesta/guide/objc/).

If there are other specific things you’d like examples of, file issues for them and one of the contributors can add them to that page.
