### ISSUE TITLE
NetworkActivityIndicatorManager + Siesta stucks forever

### ISSUE THREAD

**Issue by piv199** [bustoutsolutions/siesta#163]
Have anybody used [NetworkActivityIndicatorManager](https://github.com/Alamofire/AlamofireNetworkActivityIndicator) with Siesta + Alamofire?

I have a problem where two alamofire requests are started and only one DidFinish notification is called.. and thus network indicator spinner is stuck forever...

I'll try to make a demo project in next few days to demonstrate the problem...
All what I'm doing is adding to AppDelegate `NetworkActivityIndicatorManager.shared.isEnabled = true`

https://github.com/Alamofire/AlamofireNetworkActivityIndicator/issues/23

**Comment by pcantrell** [comment]
Yes, please put together an example project that minimally reproduces the problem.

Does the same problem occur with Siesta’s [`NetworkActivityIndicator`](https://github.com/bustoutsolutions/siesta/blob/master/Source/SiestaUI/NetworkActivityIndicator.swift#L31-L46)?

**Comment by piv199** [comment]
@pcantrell https://www.dropbox.com/sh/i8aeqd0z1o74xrh/AACFLcR3lXIqQvnaVNjBkyvZa?dl=0

No, Siesta `NetworkActivityIndicator` uses request decorators, and that's called once per each request. Otherwise `NetworkActivityIndicatorManager` is subscribing to Alamofire notifications and they are called - Resume - twice; Finished - once, thus the counter is not becoming zero.

I personally like this library, because it ensures some time before and after spinner appears/disappears...

**Comment by piv199** [comment]
I suggest not to move such functionality inside Siesta, maybe some extension to the Siesta...

I got it working with some hack:
```
        NotificationCenter.default.removeObserver(NetworkActivityIndicatorManager.shared)
        service.configure {
            $0.decorateRequests { resource, request in
                NetworkActivityIndicatorManager.shared.incrementActivityCount()
                request.onCompletion { _ in
                    NetworkActivityIndicatorManager.shared.decrementActivityCount()
                }
                return request
            }
        }
```
right after `NetworkActivityIndicatorManager.shared.isEnabled = true`.

The exact problem is in Notifications called by Alamofire... If we disable notifications by Alamofire for network activity indicator and call increment/decrement with decorate requests block then all is fine...

**Comment by piv199** [comment]
@pcantrell Hm... it seems the problem is inside AlamofireProvider...
```
    init(_ alamofireRequest: Alamofire.Request)
        {
        self.alamofireRequest = alamofireRequest
        alamofireRequest.resume()   // in case manager.startRequestsImmediately is false
        }
```

And what if `manager.startRequestsImmediately = true`? calling `alamofireRequest.resume()` fires new `Alamofire.DidResume` notification, and it increments a counter inside `NetworkActivityIndicatorManager`...

Where is the problem? We shouldn't call `alamofireRequest.resume()` on a started request, or `NetworkActivityIndicatorManager` should handle this situation?

**Comment by pcantrell** [comment]
Thanks for tracking that down, @piv199. I’d say that firing `Alamofire.DidResume` for a request that’s already started sounds like a bug in Alamofire. Someone should file that with AF.

Still, it’s reasonable to work around the issue. Does AF provide a way to test whether a request is already in progress before we call `resume()`?

**Comment by piv199** [comment]
@pcantrell 

`Alamofire.Request.task?.state` provides the current state of the task:
```
        case running
        case suspended
        case canceling
        case completed
```

**Comment by pcantrell** [comment]
It looks like we shouldn’t call resume() unless it’s suspended. Would you be interested in taking on the fix, @piv199? You’re in a good position to test it, since you can see the bug happening.
