### ISSUE TITLE
Library not loaded: @rpath/libswiftSwiftOnoneSupport.dylib

### ISSUE THREAD

**Issue by Reedyuk** [bustoutsolutions/siesta#164]
Hi Paul,
Maybe you can help me, i have a framework that I have created, it uses Siesta for the network layer. Recently i tried to add CocoaLumberJack but its now causing the following error when i run my unit tests.

https://gist.github.com/Reedyuk/0a065ec32576530abd70804f40b87017

Here is the branch.
https://github.com/Reedyuk/SwiftTemplateFramework/tree/cocoalumber

It builds fine, just when you run the unit tests it fails to run them.

**Comment by pcantrell** [comment]
It sounds like you may not be copying / emitting all the frameworks your tests need.

This SO question may be relevant:

http://stackoverflow.com/questions/40986082/dyld-library-not-loaded-rpath-libswiftswiftononesupport-dylib

**Comment by Reedyuk** [comment]
hmm, yes i had a look at this but it didn't work. I will keep looking around to see if i can find a solution.
Thanks

**Comment by pcantrell** [comment]
OK. Please do reopen if it seems to be a bug in Siesta.
