### ISSUE TITLE
Siesta wrapper around SDKs

### ISSUE THREAD

**Issue by piv199** [bustoutsolutions/siesta#165]
Hi, Paul.

I was given task to create the app that talks to the RESTful service... I would like to create the service as separate project or distribute as pod. I don't like to stick with Siesta as dependency for this service in separate project. I would like to create this server with native URLSession implementations and callbacks/delegates... So, I could distribute it and anyone could adapt to ones frameworks/libs...

In my project I would like to wrap this service/sdk/framework with Siesta. So, I would have native implementation of backend endpoints that could be used in any app and my app that uses Siesta to wrap this implementation.  Could this be achieved with Siesta? Could I wrap not direct HTTP requests with Siesta?

I'm looking forward to hear your thoughts.
Thanks! Olexii!

**Comment by pcantrell** [comment]
Olexii, I think you’ll find it awkward to do what you describe. It sounds like an overconstrained problem. You may be better off keeping two separate libs.

That said, Siesta can wrap anything that conforms to [`NetworkingProvider`](http://bustoutsolutions.github.io/siesta/api/Protocols/NetworkingProvider.html). You basically need to be able to start arbitrary requests given a `URLRequest`, and call Siesta back when they complete. If you can make your lib conform to that, then you can wrap your lib with Siesta.
