### ISSUE TITLE
Question on RequestError

### ISSUE THREAD

**Issue by BilalReffas** [bustoutsolutions/siesta#166]
Hi,

thank you first for this awesome Modul ! 
My question is does the RequestError support localization for the userMessage?

**Comment by pcantrell** [comment]
Siesta does minimal localization due diligence: it uses `NSLocalizedString` for its own error messages, and asks `HTTPURLResponse` for localized messages. However, the localization is not exhaustively tested, and Siesta does not include any localized string files itself. Pull requests welcome!
