### ISSUE TITLE
Linker error when app does not import Siesta

### ISSUE THREAD

**Issue by BilalReffas** [bustoutsolutions/siesta#169]
I receive a issue when I don't `import Siesta` in my Controller. In my Controller I `import API`.
My module API already have Siesta imported of course over `import Siesta`.
<img width="401" alt="bildschirmfoto 2017-01-16 um 11 55 54" src="https://cloud.githubusercontent.com/assets/8920003/21980445/b17bb61a-dbe3-11e6-976a-8ae591fced4e.png">
Is this a bug from Apple maybe?

**Comment by pcantrell** [comment]
This might be a Swift or Xcode bug, and it might be a configuration problem in your project. Just to be clear:

1. The seemingly unnecessary `import Siesta` in your app makes the problem go away?
2. Your `API` module uses Siesta directly?
3. Your app does not use Siesta directly, just `API`?

How are you including Siesta: CocoaPods? Carthage? submodule/subproject?

What are your project settings for **Build Phases → Link Binary with Libraries** and **Copy Bundle Resources**?

**Comment by BilalReffas** [comment]
I think it's a Swift or Xcode bug because the issue goes away for some reason. :/
