### ISSUE TITLE
Building queue for requests authentication

### ISSUE THREAD

**Issue by BilalReffas** [bustoutsolutions/siesta#170]
Hi again! 
I have a question. I would like to refresh the user token to my backend. The problem is I have other calls which will return 401 then. How I can cancel or stop all Siesta calls till I refresh successfully the token. ? Should I build a queue or can I just cancel globally all calls? 
Thank you for your support :)

**Comment by BilalReffas** [comment]
Currently we found a work around.  


```swift
private func refreshTokenOnAuthFailure(request: Siesta.Request) -> Siesta.Request {
        return request.chained {
            guard case .failure(let error) = $0.response,
                error.httpStatusCode == 401 else {
                    return .useThisResponse
            }

            if let refreshTokenRequest = self.refreshTokenRequest {
                return .passTo(
                    refreshTokenRequest.chained {
                        if case .failure = $0.response {
                            return .useThisResponse
                        } else {
                            return .passTo(request.repeated())
                        }
                    }
                )
            } else {
                return .useThisResponse
            }
        }
    }

    private var currentRefreshTokenRequest: Request?

    private var refreshTokenRequest: Request? {
        if let request = self.currentRefreshTokenRequest {
            return request
        }
        guard let token = Keychain.luubra.token,
            let refreshToken = Keychain.luubra.refreshToken else {
                return nil
        }
        let resource = self.user
            .child("refresh")
            .withParam("token", token)
            .withParam("refresh_token", refreshToken)

        self.currentRefreshTokenRequest = resource.request(.put).onSuccess {
            if let token =  $0.jsonDict["auth_token"] as? String,
                let refreshToken = $0.jsonDict["refresh_token"] as? String {
                print(token)
                print(refreshToken)
                Keychain.luubra.token = token
                Keychain.luubra.refreshToken = refreshToken
            }
                self.invalidateConfiguration()
            self.currentRefreshTokenRequest = nil
        }
        return self.currentRefreshTokenRequest
        
    }
```
Know it just make only one request. My question is if it's okay to implement it that way ? :)

**Comment by victorcotap** [comment]
I'm now using this method as well. It appears to be working fine

**Comment by BilalReffas** [comment]
Great to hear @victorcotap :)

**Comment by pcantrell** [comment]
@BilalReffas: If you are using that `refreshTokenOnAuthFailure` with `decorateRequest(…)`, as it is in the [doc example it comes from](http://bustoutsolutions.github.io/siesta/guide/configuration/#decorating-requests-via-configuration), then you are doing it right.

Reusing that single token update request for all the clients is exactly the sort of thing that the `Request` API is supposed to support: any number of callbacks, added at any time, can safely attach themselves to a request and share the answer. So your approach looks solid to me.

I’m closing this out, but please do reopen it if you find a bug or design shortcoming.
