### ISSUE TITLE
Splitting into multiple Services

### ISSUE THREAD

**Issue by codeOfRobin** [bustoutsolutions/siesta#172]
Would it be advisable to split unrelated parts of your app (even if they're the same URL), into multiple services?

For example, my login/2FA flow into a `LoginService` or something (same URL, completely different headers/auth schemes)

**Comment by pcantrell** [comment]
These are the things that operate across a service as a whole, but do not cross service boundaries:

- the resource cache
- global `configure()` (i.e. called without a pattern or predicate)
- `wipeResources()`
- `invalidateConfiguration()`
- `cachedResourceCountLimit` and the eviction of unused resources

If you want to keep any of those things strictly separate, then multiple services might make sense. It’s not common, but I could imagine situations where it’s the right thing.

The first is the really big one. If you want to simultaneously cache two different versions of the same URL to be used in two contexts, then that means two services — at least separate instances if not separate classes.

OTOH, if you want to _avoid_ having multiple cached versions of the same resource running around, then keep yourself to a single service. For example suppose your `LoginService` returns the URL of the user’s profile on successful authentication, so you do this:

    let profile0 = relativeResource(loginResult.profilePath)

Then suppose you have a `UserService` and you do this:

    let profile1 = userService.resource("/profile/me")

Now `profile0` and `profile1` belong to different services, are separate objects, and thus can potentially get out of sync. If that’s not what you want, then keep it to a single service and configure the special header scheme for auth using path wildcards.
