### ISSUE TITLE
Xcode 8.2.1 - Swift 3 compatibility issue 

### ISSUE THREAD

**Issue by Meseery** [bustoutsolutions/siesta#174]
I've podded Siesta 1.0.1 into my App and got old Swift version warning and alert to be update to Swift 3!

```
  pod 'Siesta', '>=1.0.1'
  pod 'Siesta/UI', '>=1.0.1'
```

<img width="942" alt="screen shot 2017-01-29 at 3 07 59 pm" src="https://cloud.githubusercontent.com/assets/3482174/22404240/387f4478-e635-11e6-9221-ea1589d0bcc1.png">

**Comment by pcantrell** [comment]
Siesta requires Swift 3. You'll need to change your whole project to use Swift 3 in order to use the latest Siesta. (It's currently not possible to mix Swift versions in a project.)

There are old `swift-2.2` and `swift-2.3` branches if you cannot make the Swift 3 migration now.

**Comment by Meseery** [comment]
i've Xcode 8.2.1 which comes with `Swift 3` SDK !

**Comment by pcantrell** [comment]
Yes, but those compiler errors indicate that your project is not set to use it. Search for information on setting the Swift language version in a Cocoapods project.
