### ISSUE TITLE
How to get a set of resources to load data correctly after being offline

### ISSUE THREAD

**Issue by jordanpwood** [bustoutsolutions/siesta#177]
Hey Paul!  You'll be happy to know that we've gone live with our Siesta/CouchDB powered change to our iOS app, as described [here](http://support.thirdiron.com/knowledgebase/articles/1123435-about-my-articles).  I'm happy to say that Siesta is performing like a champ and is working just as advertised, I'm very happy we chose to use it!  The offline use of Siesta with an EntityCache implementation behind it was an important feature of Siesta for us, and is also working well, with one issue as described below.

The conditions are this:  
The user has a list of articles they want to get data about, so we are chopping our list into a smaller list of URLs, each of which specifies 20 article IDs in the query.  If the user tries to look at their list while offline, we're using cached data, and it works appropriately.  However, when the user goes back online, only 1 of the `Resource`s `latestError` is not `nil`, and the others don't reload.  I've tried to step through the code and see the problem, but it works correctly when I'm stepping through it!  This makes me think there's some timing issue at play.  If you have any ideas for scenarios for me to test, please let me know.

I would love your help and advice, and keep rocking it with Siesta!

**Comment by pcantrell** [comment]
I'm delighted to hear it's working well for you in general!

I'd certainly need more detail about the problem you're encountering to diagnose it. A project that reproduces the problem is the best, of course. Logs would also be helpful. With sufficient detail, Siesta's logging should say what state those zombie resources think they're in.

**Comment by jordanpwood** [comment]
I have found a different way of triggering what I believe is the same problem.  I have an excerpt from a debug log [here](https://gist.github.com/jordanpwood/e1b8e4d481ba5cfcebf1ae5fd68b7439).

This is my first use of Siesta after app start, and my persistent cache is empty.  I request several URLs in succession.  The lines of the form "Got 	0 articles out of the cache using..." are coming out of my persistent cache, and are being triggered from Siesta.  There are 19 lines like this, so Siesta made 19 requests for cached data, which is the number I expect given the amount of data I was trying to retrieve.  The worrying part is that there are only 6 GET requests being sent for that set of 19 requests.  There are also only 6 URLs mentioned in the staleness checks.  Some are are mentioned in more than one staleness check, which I don't think should be happening, since I'm only requesting each one once.    There is a gist of the output of this set of requests being made with .all turned on for Siesta logging [here](https://gist.github.com/jordanpwood/0ee2ce70e88ce5b5ff69c795a172f838).  As you can imagine, this file is slightly bigger!

I found this problem because I'm implementing some performance improvements which have the side effect of not requesting data from Siesta quite as often when I first display a list of articles.  I hadn't noticed this problem before this point because subsequent calls to Siesta concerning the missing URLs do work.  My performance improvements are going to have to wait until we figure out what is going on in Siesta!  I have yet to be able to reproduce this problem in a test or other more controlled situation.

Let me know if you have any other tests you would like me to do.

Jordan

**Comment by jordanpwood** [comment]
Wait a sec @pcantrell!  Let me look into this some more, it might be that my "performance improvements" are asking for the wrong data!

**Comment by pcantrell** [comment]
@jordanpwood: I lost track of this issue; my apologies. Did you manage to determine if this bug was really a bug or not?

**Comment by jordanpwood** [comment]
Well, my "related problem" turned out to be something else; I wasn't properly setting the timestamp on the data coming out of my `EntitiyCache` implementation.  Its possible that my original problem was related to that, but I don't exactly know how.  I've not reproduced the original problem since I made my entity cache changes (plus some changes where I more intelligently request data from Siesta).

I'll close this issue, and reopen it if I see the problem again.

Thanks again, Paul!
