### ISSUE TITLE
How to use Resources using POST requests

### ISSUE THREAD

**Issue by ivanmkc** [bustoutsolutions/siesta#178]
Hi,

I'm rewriting a network layer from scratch using Siesta and read all the information and docs but still haven't figured out a way to  have a Resource use a POST request instead of GET.

1. I can fire off a POST request using the request(.post) function but that is one-off/
2. Also I read the the URL uniquely defines the Resource. In the case of POST requests, all the URLs are the same and the parameters are what differs. Will they be treated as the same resource?

Thanks!

**Comment by pcantrell** [comment]
This question is answered here: http://stackoverflow.com/questions/41832911/configure-request-method-for-a-siesta-resource
