### ISSUE TITLE
Persisting resource across changes to routes and parameters

### ISSUE THREAD

**Issue by ishaanSejwal** [bustoutsolutions/siesta#182]
Is it possible somehow to change the path and parameters of the same resource? I don't seem to find a way to do that, the only way I see is creating a new resource for any change in Route/parameters of the API. I currently have an API that I rather would like its resource to be updated which requires me to send different data in path and parameters for several cases but only updating the response against the same model.

**Comment by pcantrell** [comment]
In its current form, Siesta thinks that there’s a one-to-one correspondence between URLs and logical resources. You can manually propagate changes as described in this issue:

https://github.com/bustoutsolutions/siesta/issues/156

…or perhaps what you really want is to radically remap a non-RESTful API into a logical structure, as this other person asked?

https://github.com/bustoutsolutions/siesta/issues/81

The best way to do that is currently to build your own `NetworkingProvider` that translates logical URLs of your own choosing into the messy requests your real API expects.

**Comment by pcantrell** [comment]
I’m closing this assuming that the response above answered your question, but @ishaanSejwal feel free to ask for clarification or reopen if there’s a feature request the links above don’t cover.
