### ISSUE TITLE
Don't show ResourceStatusOverlay in certain scenarios

### ISSUE THREAD

**Issue by alecgorge** [bustoutsolutions/siesta#186]
First of all, thank you so much for Siesta and the awesome power of the pipeline. I've been using Siesta with [Cache](https://github.com/hyperoslo/Cache) to get a very efficient caching system (in memory, backed by the desk) for offline usage. Things have been great and I'm not even done with my project and I am encouraging everyone I know to use Siesta!

I'd like to not show the error message from ResourceStatusOverlay in the event that the follow are all true:

1. According to Reachability, they are offline
2. `latestData` has something in it

Is there any way to bend the pipeline/ResourceStatusOverlay to do this or do I need to reimplement ResourceStatusOverlay with my desired changes?

**Comment by dazzz1er** [comment]
Hi @alecgorge 

I'm not part of the team but you and I sound to be in very similar situations; I am currently developing an app using Siesta with Cache for offline features.

I was looking to get the same/similar functionality with ResourceStatusOverlay as you are, and found that if I change the overlay's `displayPriority` to `[.anyData, .loading, .error]` then this will always show the cached data, no matter how stale, if the user is offline. Essentially, if `latestData` is not `nil` on any observed resource then no error is shown.

This may not be entirely what you wanted so if you require a reliance on Reachability I suggest amending ResourceStatusOverlay slightly by adding a new case in the `StateRule` enum for your use case and then implementing your rule in the `updateDisplay` method. That way you could specify `displayPriority` as `[.yourRule, .nextRule, .loading...]` etc. for those overlays that require your specific event handling.

You may have already worked that all out and be miles ahead, but as we seem to be working in such a similar vein I thought I'd post my thoughts in case it helped!

**Comment by pcantrell** [comment]
@alecgorge: Did you get this worked out? If the approach @dazzz1er describes (or variations on it) did’t get you what you need, and you did in fact find yourself adding a new `StateRule`, let me know. I’ve toyed a bit with designs that would make `StateRule` a protocol instead of an enum so as to let people define custom ones, but didn’t have a compelling use case.

**Comment by alecgorge** [comment]
@dazzz1er @pcantrell yup that was exactly what I needed :) Sorry for not following up earlier!

It doesn't address the general scenario but it is exactly what I want.

**Comment by pcantrell** [comment]
Glad to hear it worked out for you! I can imagine ways to generalize it, but I have yet to find a case where generalizing is necessary. Let me know if you do!
