### ISSUE TITLE
Can't send image at server

### ISSUE THREAD

**Issue by ToxaZhe** [bustoutsolutions/siesta#190]
Please provide some examples how to send image using multipart/formData in base64 format and in binary. In base64 i'm only able to send 200*200 image

**Comment by ToxaZhe** [comment]
thanks Alex for reply. I'm using now base64 it works great. The problem was at server. There was a limit of 100 kb. But i tried your solution and it doesn't work. The reason is seems to be at server too.

**Comment by Alex293** [comment]
You still need to adapt the fname var tho

**Comment by ToxaZhe** [comment]
we are not using any fname. Maybe that is the reason? I'm not clearly understand why we need to send this parameters: 
body.append("--\(boundary)\r\n".data(using: String.Encoding.utf8)!)
        body.append("Content-Disposition:form-data; name=\"photo\"; filename=\"\(fname)\"\r\n".data(using: String.Encoding.utf8)!)
        body.append("Content-Type: \(mimetype)\r\n\r\n".data(using: String.Encoding.utf8)!)
        body.append(image_data!)
        body.append("\r\n".data(using: String.Encoding.utf8)!)
        
        body.append("--\(boundary)--\r\n".data(using: String.Encoding.utf8)!)

i can't understand what all this things means. Maybe you could share some link where i will be able understand more deeply uploading files logic and scheme

**Comment by Alex293** [comment]
It is the name of the image file that the server will create upon data reception and "photo" the name of the var php will use. Boundaries related code is used for multiparty to separate parts.

**Comment by Alex293** [comment]
https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2

At the very end of this page there are informations about multipart why a body example structure

**Comment by ToxaZhe** [comment]
Yes , but we are using mongoDB. And i didn't find examples with sending images to mongo. Also the backend guy creates his own name for file. So that what is the problem. But anyway i'm very appreciate for your help)))

**Comment by pcantrell** [comment]
Since this thread has turned into a discussion of multipart encoding, which is an HTTP feature and not Siesta-specific, I’m closing this issue. Please not, however, that I would happily accept a pull request for a multipart encoding helper in the spirit of the JSON and form encoding helpers [in this file](https://github.com/bustoutsolutions/siesta/blob/master/Source/Siesta/Request/RequestCreation.swift).

@Alex293, thanks for helping walk Toxa through this.

**Comment by juarezjaramillo** [comment]
@Alex293 the multipart code worked like a charm.
Thanks!

**Comment by pcantrell** [comment]
@juarezjaramillo If you're inspired to do a little extra work for the community, I’d encourage you to submit a PR [as described above](https://github.com/bustoutsolutions/siesta/issues/190#issuecomment-294267686)! Don't hesitate to open a PR for rough work in progress, or even just your code slapped in there with lots of dangling questions; I'd be happy to work with you to generalize it and make it Siesta-ready.
