### ISSUE TITLE
Update config for resource

### ISSUE THREAD

**Issue by mikaelbartlett** [bustoutsolutions/siesta#192]
I configure authentication token for my request with:

`configure("**") {
    if let token = authenticationToken {
        $0.headers["AUTHTOKEN"] = token
    }
}`

This configuration is cached in the Resource. How can purge this when a user logs out and the token is updated?

**Comment by pcantrell** [comment]
The configuration docs in the user guide answer this question:

http://bustoutsolutions.github.io/siesta/guide/configuration/#configuration-that-changes
