### ISSUE TITLE
No newData event received in custom class

### ISSUE THREAD

**Issue by rickvdl** [bustoutsolutions/siesta#194]
Hi,

I'm currently working on a class that handles a few network requests. So far all Siesta examples and trying some things on my own worked fine, I just used the code in my `UIViewController` for testing purposes. When creating the class I noticed that the same requests I tried earlier in my `UIViewController's` suddenly don't work in my custom class. I do see the `observerAdded` and `requested` event in the `resourceChanged` delegate method, but the `newData` event never gets passed to my custom class.

The stripped down version of my class looks like this:
```swift
class AuthSessionController {
    
    init() {
        
        let api = Service(baseURL: "https://jsonplaceholder.typicode.com")
        api.resource("/users").addObserver(self).loadIfNeeded()
        
    }
}

extension AuthSessionController: ResourceObserver {
    func resourceChanged(_ resource: Resource, event: ResourceEvent) {
        print(event)
    }
    
    func resourceRequestProgress(for resource: Resource, progress: Double) {
        print(progress)
    }
    
    func stoppedObserving(resource: Resource) {
        print("Stopped")
    }
}
```

And I'm instantiating the class in my `UIViewController` as normal:

```swift
override func viewDidLoad() {
      super.viewDidLoad()
        
      let authSessionController = AuthSessionController() 
}
```

But for some reason this is what I see in the log:

```swift
observerAdded
requested
```

In my previous testing I did see the `newData` event and my data as expected. Using Charles I was able to see that the requests went fine, and the `latestError` property always returns nil.
I have been debugging for the last 2-3 hours but since there really isn't a lot of code I'm running out of ideas.

Thanks in advance

**Comment by jordanpwood** [comment]
My first thought is that I see that `authSessionController` is a local variable to viewDidLoad.  Is there a strong reference to it somewhere?  I have the same question about `api` as well.

**Comment by rickvdl** [comment]
@jordanpwood 

Moving the variable above the `viewDidLoad` actually works.
Thanks!

**Comment by pcantrell** [comment]
To understand why your `AuthSessionController()` gets deallocated as soon as `viewDidLoad()` finishes, take a look at the [memory management section](http://bustoutsolutions.github.io/siesta/guide/memory/) of the Siesta user guide.

**Comment by rickvdl** [comment]
@pcantrell Thanks a lot for clarifying, will take a look at the documentation :)
BTW, I was running this on tvOS and so far it has been working perfectly.

**Comment by pcantrell** [comment]
Good to hear that it’s working on tvOS! Thanks for letting me know. I’ll check that box off on #28. Are you using Carthage, Cocoapods, or neither to include Siesta?

**Comment by rickvdl** [comment]
Sure, I prefer Cocoapods, but since the spec wasn't updated yet I am just cloning the Siesta project and adding the `.xcodeproj` to my workspace just like the submodule method [https://github.com/bustoutsolutions/siesta#git-submodule](url)

Thanks a lot :)
