### ISSUE TITLE
Siesta libraries throwing warnings in Xcode 8.3 and above

### ISSUE THREAD

**Issue by harelw** [bustoutsolutions/siesta#195]
I have Siesta v1.1.1 installed via Cocoapods 1.2.1 and see the following warnings in Xcode (currently using 8.3.2):

> .../Pods/Siesta/Source/SiestaUI/NetworkActivityIndicator.swift:9:8: File 'NetworkActivityIndicator.swift' is part of module 'Siesta'; ignoring import
> 
> .../Pods/Siesta/Source/SiestaUI/RemoteImageView.swift:9:8: File 'RemoteImageView.swift' is part of module 'Siesta'; ignoring import
> 
> .../Pods/Siesta/Source/SiestaUI/ResourceStatusOverlay.swift:9:8: File 'ResourceStatusOverlay.swift' is part of module 'Siesta'; ignoring import
> 
> .../Pods/Siesta/Source/SiestaUI/SiestaUI-ObjC.swift:10:8: File 'SiestaUI-ObjC.swift' is part of module 'Siesta'; ignoring import
> 
> .../Pods/Siesta/Source/SiestaUI/Ω_UI_Deprecations.swift:9:8: File 'Ω_UI_Deprecations.swift' is part of module 'Siesta'; ignoring import

**Comment by pcantrell** [comment]
This is an unfortunate but necessary effect of how Cocoapods handles submodules. While `SiestaUI` is a separate Swift module with Carthage and SwiftPM, with Cocoapods it all gets compiled into one module. The warning is harmless, but AFAIK there's no way to work around it.

**Comment by harelw** [comment]
Thanks for the info!

**Comment by pcantrell** [comment]
I was wrong above! As it turns out, there is a simple workaround. This is now fixed in Siesta 1.2.0.

**Comment by harelw** [comment]
Awesome, thanks!
