### ISSUE TITLE
Configuration gets called 3 times

### ISSUE THREAD

**Issue by akaralar** [bustoutsolutions/siesta#199]
I'm currently having a transformation problem and I can't exactly pinpoint the issue. 

I have a GET endpoint `/search` that works with a query parameter, as in `/search?parameter=searchTerm`

I add configuration for this endpoint using 
```swift
service.configure("/search", requestMethods: [.get]) {
  $0.pipeline.removeAllCaches()
  $0.pipeline[.model].add(DictionaryTransformer<SearchResult>())
}
```
where `DictionaryTransformer` is a transformer that takes a dictionary and parses it to struct, as in

```swift
struct DictionaryTransformer<T: Unmarshaling>: ResponseTransformer {
  func process(_ response: Response) -> Response {
    switch response {
    case .failure:
      return response
    case var .success(entity):
      guard let content = entity.content as? MarshaledObject else {
        let error = MarshalError.typeMismatch(expected: "JSON Dictionary", actual: entity.content)
        return failure(with: entity, error: error)
      }

      do {
        let object = try T(object: content)
        entity.content = object
        return .success(entity)
      } catch {
        return failure(with: entity, error: error)
      }
    }
  }
}
```

where `MarshaledObject` is a protocol that `Dictionary` [conforms](https://github.com/utahiosmac/Marshal/blob/master/Sources/MarshalDictionary.swift#L24), and is needed to initialize the generic type with `T` with `init(object: MarshaledObject)`.

Later I build requests for this resource like this:
```swift
func fetchSearchResults(for query: String) -> Request {
  let resource = service.resource("/search")
  return resource.withParam("parameter", query).request(.get)
}
```

The API returns the same dummy response for now whatever the query. The first time the response arrives, it goes into the transformer, passes the `guard` in the transformer, and comes out with the expected type of `SearchResult` without any problems. In the subsequent requests though, the type of `entity.content` in the transformer is not the input type of `Dictionary` but the output type of `SearchResult`, hence the `guard` in the transformer fails and the response fails. Since the README states that JSON responses are parsed only once, and since the API responses to all the requests are the same, I suspected that even though the resources are different (different query, hence different URL), the parsed object `SearchResult` is cached, so I added the `$0.pipeline.removeAllCaches()` to the configuration but it didn't make any difference.

Am I missing something or is this expected behaviour? If so, is there any way to override this? Or am I implementing the transformer incorrectly?

Maybe parallel to this, but while debugging I noticed that for each query, the configuration block is called 3 times. Since I am creating new resources with each query, this might be expected, but later when I inspect the `stagesAndEntries` for the resource in `PipelineProcessing.swift`, I find that `DictionaryTransformer<SearchResult>` is placed in the `transformers` array of `PipelineStage` 3 times as well. That seemed odd and since I was getting the transformed object at the beginning of a transformer, I thought it might be related, but maybe that's expected as well.

**Comment by akaralar** [comment]
Ah I found the reason for this. I was invalidating the configuration when auth token was changed, and the transformer I used was adding new transformers each time the configuration was invalidated. Adding `$0.pipeline[.model].removeTransformers()` in the `configure` block did the trick, but now it leaves me with the boring task of adding that line to each `service.configure(...)` block I have. I wish there was an easier way to remove transformers in a certain stage for all configurations. Would that be possible?

**Comment by akaralar** [comment]
I started seeing weird behaviour when I remove transformers from the pipeline. I set up my configuration for changing auth token this way, which is triggered from `didSet`: 

```swift

  var authentication: Authentication? {
    didSet {
      service.invalidateConfiguration()
      service.wipeResources()
    }
  }
init() {
  service.configure(requestMethods: [.get, .post, .delete]) {
    $0.pipeline[.cleanup].removeTransformers()
    $0.pipeline[.cleanup].add(ErrorMessageExtractor())
    $0.headers["customertoken"] = self.authentication?.token
  }

  // More configs..
}
```

But the token sometimes disappears and I start getting `401`s from the API. Since `.replaceExisting` can only be used with `configureTransformer` and not `configure` methods, actually I'm removing the transformers myself, and when I don't, they are added more than once to the pipeline. What's the correct way to evade this behaviour?

**Comment by BilalReffas** [comment]
@akaralar can you please post how you update your token from the api with a new one? I have some trouble with this :/

**Comment by akaralar** [comment]
@BilalReffas It will most certainly depend on your app, I am doing it the same way it is described here: http://bustoutsolutions.github.io/siesta/guide/configuration/

**Comment by akaralar** [comment]
@pcantrell It seems using 
```swift 
var authentication: Authentication? {
  didSet {
    service.invalidateConfiguration()
    service.wipeResources()
  }
}
``` 

doesn't remove the previous configuration, as the transformers are added each time I change the authentication. So if I change the authentication 3 times, (via logout - login), then even though configuration is invalidated, the transformers from previous configuration still remain. The configurations are done in an `init()` method that is called only once (there is only one `Service` instance and it is injected to each view model in the app), so I'm not adding them myself.

Here is a screenshot from logs of Siesta when the app first opens and there is a cached logged in user:
https://dl.dropboxusercontent.com/spa/6d4j003yz96ozkz/ppz0b7e2.png

and this one is after logging in and out a few times. Notice that it is applying previous configurations as well.
https://dl.dropboxusercontent.com/spa/6d4j003yz96ozkz/two_qpr5.png

the configurations that apply to this endpoint are as following:
```swift
init() {
  // ...
    service.configure(requestMethods: [.get, .post, .delete]) { [weak self] c in
      c.pipeline[.cleanup].add(ErrorMessageExtractor())
      c.headers["customertoken"] = self?.authentication?.token
    }

  service.configure(Endpoint.Profile.me.path, requestMethods: [.get]) {
    $0.pipeline[.model].removeTransformers()
    $0.pipeline[.model].add(DictionaryTransformer<Profile>())
  }
}
```

This seems like a bug to me, but feel free to correct me if this is intended behaviour.
