### ISSUE TITLE
Type issue when using Decodable

### ISSUE THREAD

**Issue by BilalReffas** [bustoutsolutions/siesta#204]
I'm trying to use the new Swift 4 feature with decodeable. But I'm running on a runtime issue 

> Siesta.RequestError.Cause.WrongInputTypeInTranformerPipeline(expectedType: Foundation.Data, actualType: __NSDictionaryI, transformer: Data → User)), timestamp: 519992008.24429899

This is my pipeline: `try jsonDecoder.decode(User.self, from: $0.content)`. It seems like that the `$0.content` is not a Data Object. 🤔

**Comment by pcantrell** [comment]
Siesta [configures a JSON parser in the transformer pipeline by default](http://bustoutsolutions.github.io/siesta/guide/pipeline/#default-transformers). Turn that off (per the instructions in that link) if you want raw data for JSON responses.

**Comment by BilalReffas** [comment]
Thank you for the response. I'm closing this :)
