### ISSUE TITLE
Support for Swift 4 Codable/Decodable features

### ISSUE THREAD

**Issue by 3257** [bustoutsolutions/siesta#205]
How are you guys going to handle this new features in Swift 4? And when do you think that will be?

**Comment by pcantrell** [comment]
You should be able to configure Swift 4 coders in your transformer pipeline just as you would [any other kind of model-specific mapping](http://bustoutsolutions.github.io/siesta/guide/pipeline/#model-mapping). It's not clear to me that any special support from the framework is necessary to support them.

If you try it and run into a specific roadblock, please file an issue! It is certainly Siesta’s goal to support Swift 4 when it is officially released.
