### ISSUE TITLE
Add header field that changes for every request

### ISSUE THREAD

**Issue by SilverTab** [bustoutsolutions/siesta#206]
The API that I use requires a header field that is a computed hash of various elements (the request's URL, its POST body, etc.). I was wondering if it would be possible to do something like that with the `decorateRequests` pattern, however I'm not sure how I can modify the request's headers in that block (or even access its POST body)? Should I consider doing this at a lower level?

Any help/ideas would be appreciated...

**Comment by SilverTab** [comment]
Update: I managed to achieve this by writing my own URLSession NetworkingProvider, however, I'd still be interested to know if it's possible to get to this result without having to work at the URLSession level.

**Comment by pcantrell** [comment]
Indeed, this is something of a gap in Siesta. Good point.

You can currently achieve this with the `requestMutation:` param of `Resource.request(_:)` and friends, but not via configuration. As you discovered, `decorateRequests` is for adding behavior before and after an already-constructed request, not for modifying it. Configuration should also have a place for attaching [`RequestMutation`](http://bustoutsolutions.github.io/siesta/api/Classes/Resource.html#//apple_ref/swift/Alias/RequestMutation)s to be applied _before_ the `Request` is contructed.
