### ISSUE TITLE
Disk cache lookups inconsistent?

### ISSUE THREAD

**Issue by SilverTab** [bustoutsolutions/siesta#207]
I'd like to use Siesta's persistent cache feature. I implemented a simple class conforming to the EntityCache protocol based on NSCoding that writes/read to disk just to get a sense of how the whole thing works. I manage to get most of it working, but I'm noticing a weird pattern when it comes to disk cache lookups and I'm trying to understand the reasoning behind it.

I've set the `expirationTime` on one of my resource (let's call it `foo`) to 5 seconds, and this is what I am observing:

- When the app starts, it tries to load resource `foo` which is already in the cache, it results in a cache lookup, followed by a cache hit, as expected. It also results in a network request and a cache write with the fresh data once the request succeeds, again, as expected.
- Wait for 5 second to pass, resource `foo` should be stale, but still on the disk cache. Next time the resource is loaded (with loadIfNeeded), a network request is initiated immediately and no cache lookup happens. Upon success, the expected cache write is happening.

I'm trying to figure out why this second request to my resource doesn't even trigger a disk cache lookup and immediately requests it from the network?

Ideally what I'd like to do is this: If the data is available in the disk cache, return it immediately so that I can update my UI asap, even on a slow network, while requesting fresh data from the server and updating the cache... It seems like this happens on app launch (or the first time a resource is requested), but not for subsequent requests, even if they are stale, which results in immediate network requests, and long loading time on a slow network... Reading Siesta's documentation, I was lead to believe that this was possible (this part especially from EntityCache's documentation: "The purpose of HTTP caching is to prevent network requests, but what we need is a way to show old data while issuing new requests. This is the real deal-killer.")

Am I misunderstanding something here or is it an issue with Siesta's disk cache lookup logic?

**Comment by jordanpwood** [comment]
> I'm trying to figure out why this second request to my resource doesn't even trigger a disk cache lookup and immediately requests it from the network?

I also use the persistent cache feature of Siesta, and from your description I would first recommend you look at the value of the `ResourceEvent` you are getting back in your observer.  I'm guessing that it is `.requested`.  You should get your expected stale data in your observer.  

The reason your persistent cache doesn't get hit is that Siesta has an in-memory cache which was initialized from the persistent cache, and then updated from the network request.  Your cache should only see new data to write to it until the resource in question is removed from the in-memory cache.

**Comment by SilverTab** [comment]
Oh, interesting! That would make sense. I can't test right now but I will as soon as I'm back home. I think I was actually only updating my UI on the `.newData` event, which might actually explain the slowness in updating the UI on a throttled connection that I was observing!?

Will confirm once I get back home and close this issue if that's the case! 👍
