### ISSUE TITLE
Pattern matching question

### ISSUE THREAD

**Issue by Alex293** [bustoutsolutions/siesta#211]
Hi,

I'm having troubles with some pattern matching for urls : 

api/resource -> should map to function 1
api/resource/1 -> should map to function 2
api/resource/?offset=40 -> should map to function 1 

how to differentiate an id to a request ?

**Comment by akaralar** [comment]
Your answer lies in `ConfigurationPatternConvertibale.swift` file. Taken from there:
```
/**
      Matches URLs using shell-like wildcards / globs.

      The `urlPattern` is interpreted relative to the service’s base URL unless it begins with a protocol (e.g. `http:`).
      If it is relative, the leading slash is optional.

      The pattern supports three wildcards:

      - `*` matches zero or more characters within a path segment.
      - `**` matches zero or more characters across path segments, with the special case that `/​**​/` matches `/`.
      - `?` matches exactly one character within a path segment, and thus `?*` matches one or more.

      Examples:

      - `/foo/​*​/bar` matches `/foo/1/bar` and `/foo/123/bar`.
      - `/foo/​**​/bar` matches `/foo/bar`, `/foo/123/bar`, and `/foo/1/2/3/bar`.
      - `/foo*​/bar` matches `/foo/bar` and `/food/bar`.
      - `/foo/​​*` matches `/foo/123` and `/foo/`.
      - `/foo/?*` matches `/foo/123` but _not_ `/foo/`.

      The pattern ignores the resource’s query string.
    */
```

**Comment by pcantrell** [comment]
@Alex293, did Ahmet answer your question? What he said is exactly right. The key sentence is here:

> The pattern ignores the resource’s query string.

So `api/resource/?offset=40` and `api/resource/` are identical as far as the configuration pattern matching is concerned — but `api/resource/` and `api/resource` are not. For the ID, you want to require at least one character after the trailing slash:

`api/resource/?*`

**Comment by Alex293** [comment]
Yes I managed to achieve what I wanted ! Closing this
