### ISSUE TITLE
Unable to use 'Alamofire' as a networkprovider

### ISSUE THREAD

**Issue by LavanayaV** [bustoutsolutions/siesta#216]
I have imported the 'Siesta' library by downloading through github.
I want to add 'Alamofire; as a networkprovider.
Service.init(baseURL: urlstring, useDefaultTransformers: true, networking: Alamofire.SessionManager ) I am getting error 'use of unresolved identifier 'Alamofire'.
Help me to solve this.

I want to use 'Alamofire' as a network provider for my rest api calls.

**Comment by LavanayaV** [comment]
Please give me any link which tells how to make get and post calls using siesta rest api calls, Using 'Alamofire' as a network

**Comment by KRUBERLICK** [comment]
@LavanayaV have you included `Alamofire` pod in your `Podfile`?

**Comment by LavanayaV** [comment]
Yes..
Can u please explain ne how to use it as a networkprovider


On Aug 14, 2017 1:30 PM, "Daniel Ilchyshyn" <notifications@github.com>
wrote:

@LavanayaV <https://github.com/lavanayav> have you included Alamofire pod
in your Podfile?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bustoutsolutions/siesta/issues/216#issuecomment-322124171>,
or mute the thread

**Comment by KRUBERLICK** [comment]
@LavanayaV in your Podfile include these three pods:
```
pod 'Siesta'
pod 'Siesta/Alamofire'
pod 'Alamofire'
```

Then import `Siesta` and `Alamofire` libs in your source file and instantiate a `Service`:

```
import Siesta
import Alamofire

let service = Service(baseURL: "http://some-url", useDefaultTransformers: true, networking: SessionManager.default)
```

**Comment by LavanayaV** [comment]
Im still getting the same error. It didn't worked.

Service(baseURL: "http://some-url", useDefaultTransformers: true, networking: SessionManager.default as! NetworkingProviderConvertible)

**Comment by LavanayaV** [comment]
![screen shot 2017-08-14 at 2 19 38 pm](https://user-images.githubusercontent.com/30855945/29264784-0548fe0c-80fc-11e7-813b-955dba111416.png)
![screen shot 2017-08-14 at 2 21 38 pm](https://user-images.githubusercontent.com/30855945/29264793-0b85d970-80fc-11e7-948f-b8c13c9bad76.png)

**Comment by KRUBERLICK** [comment]
@LavanayaV remove `as! NetworkingProviderConvertible`. If you installed `Siesta/Alamofire` pod it should work without cast.

**Comment by LavanayaV** [comment]
![screen shot 2017-08-14 at 2 21 38 pm](https://user-images.githubusercontent.com/30855945/29265003-f55f1372-80fc-11e7-8167-f3fe2c5e8d71.png)

**Comment by LavanayaV** [comment]
![screen shot 2017-08-14 at 2 28 49 pm](https://user-images.githubusercontent.com/30855945/29265030-0cd54774-80fd-11e7-84f4-78f04e2722d9.png)

**Comment by KRUBERLICK** [comment]
@LavanayaV that's strange. Did you run 'pod install' after changing Podfile?

**Comment by LavanayaV** [comment]
Yes 
![screen shot 2017-08-14 at 2 30 57 pm](https://user-images.githubusercontent.com/30855945/29265061-3a8ddab4-80fd-11e7-9d01-c9e6a07891f4.png)

**Comment by pcantrell** [comment]
It is possible I did something that messed up the Alamofire extension for Cocoapods with the 1.2.0 release. Would you try Siesta version 1.1.1 and see if it works for you?

**Comment by pcantrell** [comment]
@KRUBERLICK, I’m afraid I can’t reproduce your problem. I was able to use Alamofire for the networking provider in Siesta’s GithubBrowser example project without any problem.

This error:
> I am getting error 'use of unresolved identifier 'Alamofire'
…would mean that you forgot `import Alamofire`.

This error:
> Could not cast value of type 'Alamofire.SessionManager.Type' (0x608000242388) to 'Siesta.NetworkingProvider' (0x6080002605d8).
…would mean that Siesta’s AlamofireProvider code somehow isn’t being built in your project. Make sure that Cocoapods has included `Networking-Alamofire.swift` somewhere in your xcworkspace.

@LavanayaV is correct: you should _never_ need `as! NetworkingProviderConvertible`. It’s not under any circumstances going to help if the compiler says the types don't match.

**Comment by LavanayaV** [comment]
I did the project from the beginning. Its working fine, I am able to use Alamofire as a network provider.

 let provider = AlamofireProvider.init(manager: SessionManager.default)
 let myAPI = Service(baseURL: "seome-url", useDefaultTransformers: true, networking: provider)
