### ISSUE TITLE
Siesta for WordPress blog reader app (offline reading) 

### ISSUE THREAD

**Issue by lddd** [bustoutsolutions/siesta#219]
Hi there,

i am new to iOS develoment and plan to create a app based on the wordpress backend for our blog. Now i am looking for something like siesta to fetch JSON results in some easy way and even stores the data in some local way to support offline reading.

Now my question is if siesta would be fine for this kind of scenario and maybe if there are any examples?

thanks in advance

**Comment by jordanpwood** [comment]
To use Siesta for that purpose, you would need to develop your own class or struct which implements the EntityCache protocol, as described [in the reference docs](http://bustoutsolutions.github.io/siesta/api/Protocols/EntityCache.html).  Basically, you need to provide your own backend storage solution, and EntityCache specifies the way that Siesta interfaces with your implementation.

The documentation for how to go about making one of these is pretty sparse, but I have successfully made one for my app (I am not a maintainer of Siesta, just a happy user of it).  A sample implementation of EntityCache has been a goal of @pcantrell, I know, but it has not yet happened.  The only really tricky thing for me was understanding that getting the timestamp updating properly in my cache is very important for Siesta to use the cache appropriately.

**Comment by lddd** [comment]
Thanks for your kind reply. Just found out about SwitfyPress which might do better for my kind of a project.
