### ISSUE TITLE
IBInspectable placeholderImage in RemoteImageView

### ISSUE THREAD

**Issue by aoge123** [bustoutsolutions/siesta#220]
Placeholder images are IBOutlets. Making the placeholder image an IBOutlet doesn't allow you to add an image using a storyboard. I want to set the placeholderimage in a storyboard the same way I am able to set the image for a regular UIImageView. Changing the IBOutlet to IBInspectable would make that possible. Thoughts?

**Comment by pcantrell** [comment]
Makes sense to me. Is there any downside to this? If not, send a pull request!
