### ISSUE TITLE
withParam with empty strings - wrong output url

### ISSUE THREAD

**Issue by ligal** [bustoutsolutions/siesta#222]
Using -
resource("/api").withParam("x","").withParam("y","")

expected output - "/api?x=&y="
current output - "/api?x"

some web apis need all their params to find the correct route.
this is how i found out about this issue.

please advice.

**Comment by pcantrell** [comment]
Ah, that's a bug. Mysterious!

(The correct result should be `/api?x&y`, not `/api?x=&y=`. Siesta [drops the `=` for empty string param values](https://github.com/bustoutsolutions/siesta/blob/master/Tests/Functional/ResourcePathsSpec.swift#L171-L181).)
