### ISSUE TITLE
Swift 4 / Xcode 9 Compatibility

### ISSUE THREAD

**Issue by mberndt92** [bustoutsolutions/siesta#226]
It seems that Siesta is not compatible with latest Swift/Xcode version.
Trying to compile with Xcode 9 I receive the error
`Module compiled with Swift 3.1 cannot be imported in Swift 4.0`
Any plans on adding support for Swift 4 for Siesta by compiling with Swift 4 compiler?

**Comment by pcantrell** [comment]
As you apparently discovered (I see that you closed the issue shortly after opening it), there is a `swift-4` branch.

There will be an official Swift 4 release in the next few days.

**Comment by mberndt92** [comment]
Thanks for the quick reply!
Yes, apparently I wasn’t quick enough discovering the branch.
Good to hear that its going to be released in a few days actually!

Best regards,
Maximilian Berndt
iOS-Developer
foodpanda

Tel | +49 1514 2677799
Mail | m.berndt@foodpanda.com
Skype | mberndt92
Foodpanda GmbH | Schreiberhauer Str. 30 | 10317 Berlin | Germany
Sitz der Gesellschaft | Berlin, AG Charlottenburg | HRB 138224 B | USt-ID-Nr | DE 283789080  
Geschäftsführer | Benjamin Bauer, Felix Plog, Ralf Wenzel

CONFIDENTIALITY NOTICE: This message (including any attachments) is confidential and may be privileged. It may be read, copied and used only by the intended recipient. If you have received it in error please contact the sender (by return e-mail) immediately and delete this message. Any unauthorized use or dissemination of this message in whole or in parts is strictly prohibited.
