### ISSUE TITLE
Siesta/UI conflicts with app extensions

### ISSUE THREAD

**Issue by ahbou** [bustoutsolutions/siesta#228]
Hello

In my project the Siesta/UI pod is creating conflicts when having an extension inside the app.
I'm getting the following build error:

```
.../Pods/Siesta/Source/SiestaUI/NetworkActivityIndicator.swift:19:23: 
'shared' is unavailable: Use view controller based solutions where appropriate instead.
```

Everything works well when I remove the UI pod.

**Comment by pcantrell** [comment]
AFAIK, Siesta hasn’t been tested to work with app extensions.

That line that’s failing is the one that controls the net activity indicator in the status bar. Questions to resolve this issue:

- Is it even possible to control the network activity indicator from an app extension?
- If not, is there a build-time test we can use to disable this code? (Does `if #available` do the trick?)
- Are there any other app-extension-unfriendly bits in SiestaUI?

Not having developed an app extension myself, I’d certainly welcome pull requests on this one!
