### ISSUE TITLE
NetworkStub bug in siesta tests

### ISSUE THREAD

**Issue by rauanmayemir** [bustoutsolutions/siesta#231]
While trying to follow your advice at https://stackoverflow.com/questions/39827137/how-can-i-mock-resource-responses, I noticed that `NetworkStub` is a struct, so it's passed to Service by value. When you try to add a response stub:
```
networkStub.responses["/zlerp\(n)"] = ResponseStub(data: Data(count: 65536))
```
`responses` on the Service instance will still be empty.

In this case, PerformanceTests would fail if you used `onSuccess` instead of `onCompletion`.
https://github.com/bustoutsolutions/siesta/blob/master/Tests/PerformanceTests.swift

**Comment by pcantrell** [comment]
You are quite right! I believe that a previous version of that code configured the mock responses _before_ passing them to the Service init. Thanks for catching this!
