### ISSUE TITLE
Replace deprecated property, characters, with count

### ISSUE THREAD

**Issue by aoge123** [bustoutsolutions/siesta#232]
In Logging.swift, line 57, you wrote:
 
`private let maxCategoryNameLength = LogCategory.all.map { Int(String(describing: $0).characters.count) }.max() ?? 0`

This causes a warning in Xcode because characters is a deprecated property in String now.

Since Strings are collections now, you can write this:

private let maxCategoryNameLength = LogCategory.all.map { Int(String(describing: $0).count) }.max() ?? 0

**Comment by pcantrell** [comment]
Thank you for catching this! It looks like this arrived with Xcode 9.1? I confess I hadn’t actually tested Siesta with 9.1 yet.
