### ISSUE TITLE
Race condition between cache check and loadIfNeeded()

### ISSUE THREAD

**Issue by pcantrell** [bustoutsolutions/siesta#237]
When instantiating a `Resource`, Siesta checks for cached data asynchronously, updating the resource later if there is a cache hit (and if the resource hasn’t loaded fresh data in the meantime). This is good, but it creates a race condition where `loadIfNeeded` may initiate a network request if called before the cache check is done.

Instead, `loadIfNeeded()` should return a chained request that _first_ waits for the cache check if there is one in progress, and only chains to the a network request if the we got a cache miss.

([Original SO question](https://stackoverflow.com/questions/47633211/can-i-get-siesta-to-look-at-my-persistent-cache-before-making-a-network-request/47662048))

**Comment by pcantrell** [comment]
P.S. I'm still rearranging that branch a lot as I work, and occasionally force-pushing it, so beware of that if you fork it. If you want to suggest a patch to it, LMK and I’ll stabilize it so you can make a PR.

**Comment by jordanpwood** [comment]
I'm trying this branch out, with the hope that when I need to release my new functionality in about a month, it'll be ready for prime time.  Let me know if that is going to be unlikely, I can muddle along with `master` if need be.  I have found one bug with what is currently in GitHub, which is that the standard transformer for JSON decoding isn't being applied by default.  I'm having to add:

```
self.service.configure("**") { [weak self] in // all endpoints
   // stuff
   $0.pipeline.add(StandardTransformer.json)
}

```

**Comment by pcantrell** [comment]
My grades go in tomorrow, then teaching is done for the semester! New Siesta release next week, most likely.

> the standard transformer for JSON decoding isn't being applied by default

Curious. That’s on the `file-cache` branch?

**Comment by jordanpwood** [comment]
>Curious. That’s on the file-cache branch?

Yep.

**Comment by jordanpwood** [comment]
I will say that I haven't tested that my particular setup gets the standard transformer applied on `master`.  I just removed from my code the following:

```
            //$0.pipeline[.parsing].add(strongSelf.SwiftyJSONTransformer, contentTypes: ["*/json"])

```

I used to use SwiftyJSON for all my data, but I am transitioning to using `JSONDecoder`.

**Comment by jordanpwood** [comment]
I figured out my transformer problem @pcantrell!  I realized today that the transformers were only not being applied in my unit tests, and lo and behold, I was adding my URL mocking like this:
```service = Service(baseURL: expectedV2Host, standardTransformers: [], networking: testConfig)```

😅 
As I suspected, something was off in my configuration!  I removed the `standardTransformers: []` bit, and everything is good.
