### ISSUE TITLE
setting RemoteImageView.imageURL with value of nil returns a ":"

### ISSUE THREAD

**Issue by Fritiof** [bustoutsolutions/siesta#249]
Hello,

When initializing our SettingsViewController we set the users avatar from a store containing user information. The users image url property might be nil, and if it is and that is set on a RemoteImageView's imageURL and then read, the resulting value is a semi colon.

![image](https://user-images.githubusercontent.com/15021423/39515695-31e2b65c-4dfb-11e8-9f91-60f4c3604050.png)

  - Siesta (1.3.0):
    - Siesta/Core (= 1.3.0)
  - Siesta/Core (1.3.0)
  - Siesta/UI (1.3.0):
    - Siesta/Core

**Comment by pcantrell** [comment]
Siesta internally normalizes all invalid URLs to `":"`, a syntactically valid but never functional URL, in order to funnel URL formatting errors through the same error event mechanism as other resource errors.

This is leaking out through RemoteImageView, and I agree that it shouldn’t!
