### ISSUE TITLE
Add documentation around caching behavior

### ISSUE THREAD

**Issue by axandreo** [bustoutsolutions/siesta#252]
There is little, well actually no, documentation in the User Guide explaining how caching in Siesta works. It's a little inconvenient. For example, I had to skim through the source code to figure out when Siesta attempts to load data from the cache: it involves some function like initializeFromCache which is invoked from observersChanged and observersChanged gets invoked when adding observers to a resource.  While EntityCache does have it's own section in the API docs, it would be nice to have some accompanying explanation in the User Guide to fill in missing information like this (where else does a resource load data from the cache?) or provide best practices, if any.

**Comment by pcantrell** [comment]
Caching in the current release is a bit half-baked. The behaviors you're looking at also have a subtle bug (#237).

A revamp of caching is coming, including a working default cache implementation. You can get a preview on the `file-cache` branch. (Note that the API on that branch is still in flux! It does work, though.) That branch will land with better docs.

**Comment by axandreo** [comment]
Fantastic! Can't wait. My apologies for re-opening this issue, in another issue. I didn't realize you closed it. Thank you.
