### ISSUE TITLE
When I do logout with wipeResources and invalidateConfiguration, I expect cache to be cleaned, but it is not

### ISSUE THREAD

**Issue by anatolyw** [bustoutsolutions/siesta#263]
I have following service API configuration:
```
class MyAPI {

    static let sharedInstance = MyAPI()

    private let service = Service(baseURL: "http://localhost:9000/ws/rest/service", standardTransformers: [.text, .image])

    private init() {
        let jsonDecoder = JSONDecoder()
        service.configure("/beacons") {
            $0.expirationTime = 60 * 60 // 1 hour
        }
        service.configure("**") {
            $0.headers["Authorization"] = self.basicAuthHeader
        }
        service.configureTransformer("/beacons") {
            try jsonDecoder.decode(SearchResults<Beacon>.self, from: $0.content).ibeacons
        }
    }

    func beaconList() -> Resource {
        return service.resource("/beacons")
    }
}
```
`basicAuthHeader` & Log In / Out functionality are both implemented one-to-one like in the official Siesta GitHub browser example. So, whenever `basicAuthHeader` is set I wipe all service resources and invalidate configuration:
```
    func logIn(username: String, password: String) {
        if let auth = "\(username):\(password)".data(using: String.Encoding.utf8) {
            basicAuthHeader = "Basic \(auth.base64EncodedString())"
        }
    }
    func logOut() {
        basicAuthHeader = nil
    }
    var isAuthenticated: Bool {
        return basicAuthHeader != nil
    }
    private var basicAuthHeader: String? {
        didSet {
            service.wipeResources()      
            service.invalidateConfiguration() 
         }
    }
```

**Issue is following**:

I perform following list of calls:
1. MyAPI.sharedInstance.beaconList => 401 Unauthorized => OK
2. MyAPI.sharedInstance.logIn => OK
3. MyAPI.sharedInstance.beaconList => JSON list => OK
4. MyAPI.sharedInstance.logOut => OK
5. MyAPI.sharedInstance.beaconList => JSON list (from cache) => **WRONG** - my expectation that cache have to be cleaned independent from expirationTime 1 hour.

**Comment by anatolyw** [comment]
After deeper research I have found that issue was on the server side as the server first check if the session is valid and if not only then verify presents of Authorization header. As result, after logout and wiping all resources, 5th call from above sequence has finished successfully because the session was still valid. So, I got response results cached for another one hour. 

Solution is to reset URL session. NOTE: that will still keep session valid on the server side. If you want to invalidate server session as well then you have to call server logout method first if it is available. 

To fix my issue I have performed following changes in the code:
```
class MyAPI {

    static let sharedInstance = MyAPI()

    private let urlSession: URLSession  // NEW keep urlSession to have chance for reset
    private let service: Service        // MOVE initialization into init()
    
    private init() {
        
        // NEW: Init session as you like. Ephemeral is default by Siesta 
        let config = URLSessionConfiguration.ephemeral
        config.timeoutIntervalForRequest = TimeInterval(60)
        config.timeoutIntervalForResource = TimeInterval(30)
        urlSession = URLSession(configuration: config)

        // NOTE: provide urlSession into Service constuctor
        service = Service(baseURL: "http://localhost:9000/ws/rest/service", standardTransformers: [.text, .image], networking: urlSession)

        // rest part of the init() code
    }

    private var basicAuthHeader: String? {
        didSet {            
            urlSession.reset() {} // NEW: From Apple doc: Empties all cookies, caches and credential stores, removes disk files, flushes in-progress downloads to disk, and ensures that future requests occur on a new socket.
            service.wipeResources()
            service.invalidateConfiguration() 
        }
    }

    // rest part of the class

}
```
**Proposal**:
-	Add to Service class session reset method;

**Comment by pcantrell** [comment]
I’m glad to hear you figured this out.

A clarification: you mention the server checking if the “session is valid.” Is your server using cookie-based sessions? Was `URLSession` caching your credentials somehow? Or was the problem something else?

(I’m wondering whether there’s anything here that needs to be documented better.)

**Comment by anatolyw** [comment]
Our Java server uses embedded Jetty. First class which comes to the game is AuthenticationFilter, which makes following in doFilter:

```
        if (httpSession != null && httpSession.getAttribute(USER_CONTEXT_KEY) != null) {
            // already authorized, nothing to do anymore
            chain.doFilter(req, resp);
            return;
        }

        if (!checkAuthorization(request, response, chain)) {
                return;
        }
```
So, the Authorization header is not validated so far that special key is stored in a session. 

In Siesta URLSession class is hidden inside and there is not much control over it.

YES, it would be nice to have either better documentation around session management or small set of functions to manipulate with it without keeping its own reference in ServerAPI class as in my workaround above.

**Comment by pcantrell** [comment]
Without knowing your particular Jetty configuration, we can’t know for sure how you’re told it to track your `httpSession` — but it’s probably cookie-based, in which case it’s up to you to configure your `URLSession` to store or not store the cookie as you want it to. (Alternatively, you can disable `URLSession` cookie handling entirely and then manually manage the `Cookie` header yourself.)

I’ll add a note in the documentation about cookies being managed by the underlying network provider.
