### ISSUE TITLE
Add OS X support

### ISSUE THREAD

**Issue by pcantrell** [bustoutsolutions/siesta#27]
- [x] Add OS X target
- [x] Either make iOS-specific code build conditionally or move it to a separate framework
- [x] Prove viability with a test app
- [x] Get specs running on OS X
- [x] Add OS X environment(s) to Travis build matrix

(Looks like @onekiloparsec may be working on this on a fork?)

**Comment by onekiloparsec** [comment]
Hi. Yes I did a fork because I needed an OSX target. It is not entirely obvious since there are some UIKit stuff involved. As for now, I still have to make it work for my project. But as soon as I can, I'll make a pull request.

**Comment by pcantrell** [comment]
Sounds great. Send the PR once you feel like it’s basically working, even if it’s not perfect, and I’ll review it.

The UIKit stuff should be limited to the two UI classes (`ResourceStatusOverlay` and `RemoteImageView`) … right? You should be able to just remove those files from the OS X build target.

**Comment by pcantrell** [comment]
Ah, no, looking it over, I see that there’s also a mention of `UIImage` in the response transformers, and a mention of `UIApplicationDidReceiveMemoryWarningNotification` in the weak cache. That second one is problematic, since Siesta relies on the low memory warning to keep the cache from growing without bound. I’ll have to implement the LRU cache eviction I’ve been avoiding to make that work….

**Comment by pcantrell** [comment]
Depends on #31

**Comment by pcantrell** [comment]
Fixed in #56
