### ISSUE TITLE
tvOS Carthage compilation broken for Xcode 9

### ISSUE THREAD

**Issue by jordanpwood** [bustoutsolutions/siesta#271]
I tried to get the Siesta tests running on my local machine, however, Carthage couldn't compile Nocilla for tvOS.  I got the following error message:

```
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/woodj/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/Nocilla/bd7ec7caa0576f08c00bbbf993a9204f93be16e3

Build settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvsimulator11.4

xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:tvOS Simulator, id:ECE73D0A-02FC-4B82-A5CA-FF2A9EBD7C09 }

	Ineligible destinations for the "Nocilla tvOS" scheme:
		{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Generic tvOS Device }
		{ platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Generic tvOS Simulator Device }
```

If I'm reading that right, it wants a tvOS simulator which is version 11.4, but since I'm not yet on Xcode 10, I only have access to devices up to 11.3.  Can we fix this so that tvOS can compile in Xcode 9?  If that's not the problem, how do I fix this?

**Comment by pcantrell** [comment]
@victorcotap You got the tvOS support in the project. Did you manage to get the tests running on your machine?

**Comment by pcantrell** [comment]
I believe this is resolved with the official tvOS support in Siesta 1.5.
