### ISSUE TITLE
Pods/Siesta/Source/Siesta/Support/WeakCache.swift:14:66: 'UIApplicationDidReceiveMemoryWarning' has been renamed to 'UIApplication.didReceiveMemoryWarningNotification'

### ISSUE THREAD

**Issue by danysz** [bustoutsolutions/siesta#275]
I got this error after updating to Siesta 1.4.1 with Xcode 10 and Swift 4.2

**Comment by pcantrell** [comment]
This is fixed on master (see #273, #274). I didn't cut a release yet because I realized Siesta should really support both 4.1 and 4.2 using compilation conditionals.
