### ISSUE TITLE
Readme 404 link

### ISSUE THREAD

**Issue by korywka** [bustoutsolutions/siesta#281]
Broken link: https://bustoutsolutions.github.io/siesta/api/Classes/RemoteImageView.html

**Comment by mgrider** [comment]
This link also exists in the documentation on this page: https://bustoutsolutions.github.io/siesta/guide/ui-components/

**Comment by mgrider** [comment]
FWIW, the class does still exist in the repo here: https://github.com/bustoutsolutions/siesta/blob/master/Source/SiestaUI/RemoteImageView.swift
