### ISSUE TITLE
 unexpected duplicate task error for new Xcode  build system from Xcode 10 IOS 12.0.1

### ISSUE THREAD

**Issue by NermeenNery** [bustoutsolutions/siesta#282]

**Comment by pcantrell** [comment]
This isn’t nearly enough information to diagnose or reproduce the issue. Mozilla’s guidelines are a pretty good reference on writing useful bug reports: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines

I’m closing this assuming it’s duplicate of https://github.com/bustoutsolutions/siesta/issues/242.
