### ISSUE TITLE
Support HTTP2?

### ISSUE THREAD

**Issue by a11enwong** [bustoutsolutions/siesta#29]
Debug info:

[Siesta:Network] GET https://domain.com/v1/feeds
[Siesta:Network] – ← GET https://domain.com/v1/feeds
[Siesta:StateChanges] Siesta.Resource(https://domain.com/v1/feeds)[] received error: Error(userMessage: "The operation couldn’t be completed. Protocol error", httpStatusCode: nil, entity: nil, cause: Optional(Error Domain=NSPOSIXErrorDomain Code=100 "Protocol error" UserInfo={NSErrorPeerAddressKey=<CFData 0x7fd040c43980 [0x103aeb7b0]>{length = 16, capacity = 16, bytes = 0x100201bb77…

**Comment by tracicot** [comment]
What was the solution?

**Comment by pcantrell** [comment]
Siesta should support HTTP/2 just fine as long as the underlying networking provider supports it. The default provider is `URLSession` (formerly `NSURLSession`), which supports HTTP/2 as of iOS 9.

@tracicot: If you find a case where `URLSession` supports a request when used directly but fails when used through Siesta, please open an issue.

**Comment by JoiMeseery** [comment]
I got the same issue here with iOS 11, Xcode 9 :
`UserInfo={NSErrorPeerAddressKey=<CFData 0x60400028d2f0 [0x1083299b0]>{length = 16, capacity = 16, bytes = 0x100201bb0de526680000000000000000}, _kCFStreamErrorCodeKey=100, _kCFStreamErrorDomainKey=1`

> "The operation couldn’t be completed. Protocol error"

**Comment by pcantrell** [comment]
@JoiMeseery That’s an error coming from the underlying networking layer. Same question as above: what happens when you send the same request with URLSession? If there’s a request that works with raw URLSession but not when sent through Siesta, then reopen this issue.
