### ISSUE TITLE
Can you provide an example of upload image?

### ISSUE THREAD

**Issue by a11enwong** [bustoutsolutions/siesta#30]
Using form-data

**Comment by pcantrell** [comment]
Use the `Resource.request()` variant that passes you an `NSMutableURLRequest`, and populate that exactly as you would if you were using `NSURLSession` without Siesta.

See [the API docs](http://bustoutsolutions.github.io/siesta/api/Classes/Resource.html#/s:FC6Siesta8Resource7requestFS0_FTOS_13RequestMethod15requestMutationFCSo19NSMutableURLRequestT__PS_7Request_) for an example.
