### ISSUE TITLE
Xcode SPM will not accept Quick@around-each dependency

### ISSUE THREAD

**Issue by woolsweater** [bustoutsolutions/siesta#308]
Attempting to add Siesta as a dependency via the Xcode 11 File > Swift Packages > Add Package Dependency… method results in an error complaining about "incompatible dependencies"

> the package siesta[https://github.com/bustoutsolutions/siesta] @ 1.5.0 contains incompatible dependencies:
>        quick[https://github.com/pcantrell/Quick] @ around-each

<img width="698" alt="Screen Shot 2020-04-08 at 8 47 46 PM" src="https://user-images.githubusercontent.com/761245/78856251-137d5100-79db-11ea-9b55-359dc627d5ce.png">

And indeed, it doesn't look like Quick (or at least that fork) is compatible with SPM?

(I am using Xcode 11.3)

**Comment by pcantrell** [comment]
Are you also using Quick in your own project?

**Comment by woolsweater** [comment]
I am not. Sorry, should have specified: this was a new, otherwise-empty iOS project.

**Comment by pcantrell** [comment]
Interesting, I’m able to reproduce locally — but it works if I add the dependency on Siesta using `master` instead of a version specifier. See if that workaround works for you as well, and I’ll investigate tomorrow.

**Comment by woolsweater** [comment]
Yes; interesting, that works and I saw it checking out Quick as well as your fork. Thanks for the suggestion!

**Comment by pcantrell** [comment]
Apparently SwiftPM simply doesn’t allow you to declare a versioned dependency on a package that depends on something by branch. Guess I’ll have to work on getting that around-each PR finished!

**Comment by pcantrell** [comment]
This should now be fixed if you update your Siesta dependency to ≥ 1.5.1.

**Comment by woolsweater** [comment]
That does indeed work. Thanks!
