### ISSUE TITLE
The package product 'Alamofire' requires minimum platform version 10.0 for the tvOS platform, but this target supports 9.0

### ISSUE THREAD

**Issue by omidontop** [bustoutsolutions/siesta#312]
I recently switched to SPM and when building my cross-platform Swift Package for a Generic tvOS Device, I receive this error:

```
Build target Siesta_Alamofire with configuration Debug
error: The package product 'Alamofire' requires minimum platform version 10.0 for the tvOS platform, but this target supports 9.0 (in target 'Siesta_Alamofire' from project 'Siesta')
```

I presume that this is due to the a mismatch between the minimum supported tvOS version of the [Alamofire](https://github.com/Alamofire/Alamofire/blob/2777659076fda38bd4e487739ee331c7a65b5924/Package.swift#L31) library which is 10 and that of [Siesta](https://github.com/bustoutsolutions/siesta/blob/41663b47e309cf301004bc3edbf76e92fd795f91/Package.swift#L9) which is 9.

**Comment by omidontop** [comment]
Strange but I don't get the error anymore. Will re-open it if it comes back.

**Comment by pcantrell** [comment]
Thanks for the report, Omid. SwiftPM has some caching behavior that's occasionally a bit too sticky, so maybe that's it? Do reopen if it reappears.

**Comment by omidontop** [comment]
@pcantrell You're right, that must be the case! I will!
