### ISSUE TITLE
Cannot upload to app store

### ISSUE THREAD

**Issue by rayfix** [bustoutsolutions/siesta#33]
With pod 'Siesta', '>=1.0-beta.6'
building archive is successful and validation is successful but when I try to upload to iTunes connect I am presented with the following:

<img width="583" alt="screen shot 2016-01-17 at 2 43 40 pm" src="https://cloud.githubusercontent.com/assets/137963/12380489/ffdeecb2-bd28-11e5-8ae4-cdeb18d0b4cc.png">

ugh...  My workaround was to change my version to something like 0.1.6.

**Comment by pcantrell** [comment]
Thanks for this, Ray, Are you using Cocoapods? If so, it’s probably a dup of #24, which is really https://github.com/CocoaPods/CocoaPods/issues/4421.

**Comment by pcantrell** [comment]
It looks like Cocoapods 1.0b2 fixes this:

    gem uninstall cocoapods
    gem install cocoapods --pre

(I had to uninstall the existing versions to get the `pod` command to start picking up the beta.)

Could you give that a try and let me know if that fixes it for you? Assuming that you’re using Cocoapods, that is….

**Comment by rayfix** [comment]
Thanks for the reply!  Yes, I am using Cocoapods.  Probably works but I will verify it either today or tomorrow.

**Comment by pcantrell** [comment]
Great! Close the issue if it works, and keep sending the diagnostics if it doesn’t!

**Comment by rayfix** [comment]
Worked like a charm!  Thank you as always @pcantrell
