### ISSUE TITLE
configureTransformer returns double-optional content

### ISSUE THREAD

**Issue by andrewloyola** [bustoutsolutions/siesta#35]
Checking to see if there are any examples or tips on using ObjectMapper for model mapping in Siesta. 

I think something as simple as this should work, where User is a working ObjectMapper Mappable model, and I'm using the SwiftyJSON global transformer from @pcantrell  [here](http://stackoverflow.com/a/33556327).

        configureTransformer("/profile/") {
            Mapper<User>.map($0.content as JSON) //error: type of expression is ambiguous without more context
        }

**Comment by pcantrell** [comment]
ObjectMapper seems like such a natural partner for Siesta, I’ve heard people talk about it — but I haven’t used it myself, and don’t know of any example code.

Could your problem be as simple as missing parens?

    configureTransformer("/profile/") {
        Mapper<User>().map($0.content as JSON)
    }

Also, it’s not clear to me that ObjectMapper works with SwiftyJSON — but you should be able to pass it a raw dict as parsed by Siesta:

    configureTransformer("/profile/") {
        Mapper<User>().map($0.jsonDict)
    }

**Comment by andrewloyola** [comment]
Ah, yes the parens definitely needed to be added, but does not fix the problem.  Unfortunately removing the global SwiftyJSON transformer and instead using the raw jsonDict seems to have the same problem too

**Comment by andrewloyola** [comment]
Some progress!
        
      configureTransformer("/profile/") {
            Mapper<User>().map($0.content as Dictionary)
        }

this is close! , but now I'm having trouble grabbing the data from the resource in the closure.  currently using this, which does not work.:

                if let user: User = resource.typedContent() {
                    self?.refreshText(user)
                }

or this:

                if let user = resource.latestData?.content as? User {
                    self?.refreshText(user)
                }

refresh text is never called, but I do see the below in the debugger, so I know that the object is in there somewhere...

<img width="474" alt="screenshot 2016-01-20 13 50 17" src="https://cloud.githubusercontent.com/assets/1688758/12459555/5c9dd048-bf7d-11e5-9c5e-1ac3e73c1170.png">

is there a good way to get at it?

**Comment by andrewloyola** [comment]
ok this seems to fully work for accessing the data.  it seems like one too many unwraps, but since resource.latestData.content ends up as a User? from the transformer, I had to do this:

                if let optionalUser: User? = resource.typedContent() {
                    if let user = optionalUser {
                        self?.refreshText(user)
                    }                    
                }

**Comment by pcantrell** [comment]
Ah, yes, welcome to the wonderful world of Swift’s type inference: 80% awesome, 20% wat?! Anyway, glad you figured it out.

I’m puzzled that thing didn’t compile:

    if let user: User = resource.typedContent() {

It works for me when I try to construct a parallel case. I’m wondering … does this compile for you?

    if let user = resource.typedContent() as User? {

What about this one (even though it obviously always returns nil)?

    if let text: String = resource.typedContent() {

**Comment by andrewloyola** [comment]
Sorry! I should have been more clear, all of your examples do indeed compile, but none of them succeed in unwrapping at runtime.

I think the second one:

    if let user = resource.typedContent() as User? {

should work, based on what I see in the debugger, but it fails to unwrap like the others.

**Comment by pcantrell** [comment]
Hmm, looking a little closer at the ObjectMapper API, I think Siesta is giving you content of type `User??`. Yuck.

Would you mind running this check to verify the theory?

    print("--------->", resource.latestData?.content.dynamicType)

If you see `Optional(Swift.Optional<MyProject.User>)`, then bingo.

(Minor aside: it’s both legal and idiomatic Swift to say `if let user = user`. The non-optional one shadows the optional one within the if’s body, so you don’t have to define a separate `optionalUser`.)

**Comment by andrewloyola** [comment]
Yup, with that print()

    ---------> Optional(Swift.Optional<SwiftAPI.User>)

also, appreciate the tip on optionalUser.

**Comment by pcantrell** [comment]
OK, thanks! I think that’s something I can address in Siesta. I’ll send you a fix on a branch to test when I’ve had a chance to sit down with it.

**Comment by andrewloyola** [comment]
thanks, looking forward to it!

**Comment by pcantrell** [comment]
I think I’ve fixed this on master. Give it a whirl if you get a chance, and let me know if you’re still getting the double optional!

**Comment by andrewloyola** [comment]
Confirmed as fixed, sorry for the delay.  much appreciated @pcantrell 

   ---------> Optional(SwiftAPI.User)

**Comment by pcantrell** [comment]
No worries. Thanks for verifying!

**Comment by andrewloyola** [comment]
@pcantrell just curious, any plans to properly add a release with this change?

**Comment by pcantrell** [comment]
It will be in the next beta for sure, though Siesta work is on hold for a couple of weeks for the start of the semester.

**Comment by andrewloyola** [comment]
got it. thanks!

**Comment by o15a3d4l11s2** [comment]
Is this change included in the latest released version?

**Comment by pcantrell** [comment]
@o15a3d4l11s2 No, you’ll have to use master for now.

**Comment by yehe01** [comment]
@pcantrell Hi,
This fix has not been merged to V1.0 right?
Which installation method should I follow to use master branch?
I am using cocoapod.
Thanks.

**Comment by o15a3d4l11s2** [comment]
@yehe01, if using Cocoapods, you could set the pod as
`pod 'Siesta', :git=>'https://github.com/bustoutsolutions/siesta'`
This will make Cocoapods use the master branch.

**Comment by pcantrell** [comment]
This was merged and released over a year ago. If you’re having trouble with double optionals, please file a new issue with a reproducible test case.
