### ISSUE TITLE
Easy cookies management

### ISSUE THREAD

**Issue by nabbestemmia** [bustoutsolutions/siesta#38]
I don't find it easy to add or remove the cookies in the request header.
Is it possible to add a function expressly to manage the cookies?
Or should't the client at least manage the cookies by itself, depending on the response header?
I couldn't login with my application, because the client seems to ignore the "set-cookie" in the server response header, and it fails to send the cookies back in the following requests.

**Comment by pcantrell** [comment]
Cookie-based auth in an API (as opposed to a web site) is unusual and somewhat unorthodox, so I wouldn’t want to build special handling for it directly into Siesta itself.

If you do need cookie handling, that’s a responsibility that’s best left to the underlying networking library plus your app-specific rules for allowing & storing cookies. You’d add your own [`beforeStartingRequest`](http://bustoutsolutions.github.io/siesta/api/Structs/Configuration.html#/s:FV6Siesta13Configuration21beforeStartingRequestFRS0_FFTCS_8ResourcePS_7Request__T_T_) hook to add cookie headers before sending the request, then receive cookie headers on receiving the response. That could even make a nice little lib.

For examples of the code you’d need to put in the `beforeStartingRequest` hook, see:

https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/URLLoadingSystem/CookiesandCustomProtocols/CookiesandCustomProtocols.html
http://stackoverflow.com/questions/29596206/how-to-get-cookie-from-a-nsurlsession-with-swift

**Comment by nabbestemmia** [comment]
Thank you, I'll follow your advices; I haven't other options, since I don't own the server side

**Comment by pcantrell** [comment]
Yes, we often have to make things work well with the APIs we’re given.

I’ll close this for now, but please do ask if you hit a snag with your Siesta configuration. The basic structure will be something like this:

```swift
service.configure {
  addStoredCookiesTo($0.config.headers)

  $0.config.beforeStartingRequest {
    _, req in
    req.onSuccess {
      entity in
      storeCookiesFrom(entity.headers)
    }
  }
}
```

```swift
func addStoredCookiesTo(inout headers: [String:String]) {
  // for each stored cookie
    header[cookieKey] = formattedCookieValue
}

func storeCookiesFrom(headers: [String:String]) {
  // parse any cookie headers
  if newCookieDetected {
    // store cookie
    service.invalidateConfiguration() // crucial!
  }
}
```

**Comment by nabbestemmia** [comment]
Ok, thanks a lot!

**Comment by reubenwalkerau** [comment]
@pcantrell did you solve this? I have the same requirement to receive and send back a cookie but can't get it to work.
