### ISSUE TITLE
Attaching response transformers depending on the request rest method (put/post...)

### ISSUE THREAD

**Issue by majorgilles** [bustoutsolutions/siesta#43]
Hello,

First of all, thanks for making this library which simplifies a lot of my work.

I was wondering if there was a way to attach a specific transformer to a route but only if the request method if POST/PUT/DEL/GET. Currently, my API is designed so that only the method differs, not the url, and quite a few apis are like this.

Is there an easy way to attach a transformer depeding on the rest method?

Best regards,
Gilles Major

**Comment by pcantrell** [comment]
The short answer is no there isn't — though there clearly should be, and I'm wondering why I haven't hit this already. I think the answer is that in the APIs I've used Siesta with, all non-GET requests have returned either full entities or subsets thereof.

Siesta should do this, and it should be in the 1.0 release. Putting it on the list.

**Comment by majorgilles** [comment]
Ok thanks for your answer.

The current, and easiest temporary solution is attaching manually a transformer each time a ressource is accessed.

For example, for a resource of type Patient extending service,
for getPatients(), I would attach a transformer expecting an json array
for savePatient() (which returns the original json with valid id field filled in), I would attach a transformer expecting a json object

Not the cleanest solution but it will do for now
