### ISSUE TITLE
Expose public API for creating Requests with pre-send failure

### ISSUE THREAD

**Issue by VDKA** [bustoutsolutions/siesta#44]
I am using [JSONCore](https://github.com/tyrone-sudeium/JSONCore) which provides a more native swift experience for working with JSON and have configured transformers no problem, however the `request(_: RequestMethod, json: NSJSONConvertible) -> Request` method is incompatible with the way JSONCore stores parsed JSON. I thought, no issue, I will extend Resource to add my a method with the signature `request(_: RequestMethod, json: JSON) -> Request` and follow the Siesta implementation. The issue I have run into is I cannot return a `FailedRequest` since it is internal. This is the only thing stopping me implementing this, is there a reason for this to be marked `internal`?

**Comment by pcantrell** [comment]
Your diagnosis is exactly correct, and yes, you should be able to add your own `request(…)` flavors in exactly the manner of Siesta’s own. The reason I’ve hesitated to expose `FailedRequest` is simply that I don’t want to make a public promise about that type existing, i.e. I don’t want code relying on being able to do `if request is FailedRequest { … }`.

My thought was to leave `FailedRequest` an internal type, but instead expose some sort of public factory method — probably a static method on `Request` — to create them. I’d happily accept a PR for that if you want to take a crack at it!

**Comment by VDKA** [comment]
It won't be so easy to have a static method on the protocol type `Request`. Protocols do not interact so neatly with static methods. For example
```swift
extension Request {
  static func requestFailure(error: Error) -> Request {
    return FailedRequest(error)
  }
}

func alwaysFails() -> Request {
  return Request.requestFailure(error: Error(userMessage: "Who else but failure", cause: Error.Something)
}
```

The call to `Request.requestFailure` fails to compile with the error `Static member 'requestFailure' cannot be used on instance of type 'Request.Protocol'`

Thoughts?

**Comment by pcantrell** [comment]
Right, no static members on protocols in Swift.

Hmm. I’d say make it an instance method on `Resource` then. Although there’s no backreference from the request to the resource, it does seem kind of right to ask a resource for an associated request in _all_ cases. Maybe.

Let’s try that and how it smells.
