### ISSUE TITLE
Response transformer for JSON with associated objects

### ISSUE THREAD

**Issue by ezescaruli** [bustoutsolutions/siesta#46]
Hi,

First of all, nice work on this library!

From what I read/tried about how JSON responses are parsed, I could see that the way to do it is something like:

JSON (notice that all `cars` have the same `user`):
```
{
  "cars": [
    {
      "model": "Ford",
      "user": {
        "username": "exampleuser",
        "email": "exampleuser@example.com"
      }
    },
    {
      "model": "Chevrolet",
      "user": {
        "username": "exampleuser",
        "email": "exampleuser@example.com"
      }
    },
    {
      "model": "Renault",
      "user": {
        "username": "exampleuser",
        "email": "exampleuser@example.com"
      }
    }
  ]
}
```

Models:
```
import SwiftyJSON

class Car {
    var model: String!
    var user: User!
    
    init(json: JSON) {
        self.model = json["model"].string
        self.user = User(json: json["user"])
    }   
}

class User {
    var username: String!
    var email: String!
    
    init(json: JSON) {
        self.username = json["username"].string
        self.email = json["email"].string
    }
}
```

Transformer:
```
service.configureTransformer("/cars") {
    ($0.content as JSON).arrayValue.map(Car.init)
}
```

However, turns out that our APIs often respond with JSONs formatted in a different way: that is, having associated objects instead of nested ones, so shared objects are not included more than once. For example, the one above would look like this, with only one `user` object in the response:
```
{
  "cars": [
    {
      "model": "Ford",
      "user_id": "1"
    },
    {
      "model": "Chevrolet",
      "user_id": "1"
    },
    {
      "model": "Renault",
      "user_id": "1"
    }
  ],
  "users": [
    {
      "id": "1",
      "username": "exampleuser",
      "email": "exampleuser@example.com"
    }
  ]
}
```

Is there any way to configure a transformer to handle this responses in a neat way?

Thanks!

**Comment by pcantrell** [comment]
A transformer can do arbitrary processing (as long as it follows Siesta’s [thread safety conventions](http://bustoutsolutions.github.io/siesta/guide/threading/)), and it can return any sort of data structure you like.

This is therefore really more of a Swift question than a Siesta question.

Here’s a quick and dirty sketch to get you started:

```
service.configureTransformer("/cars") {
    (content: JSON, _) in

    let users = content["users"].arrayValue
    func findUser(id: String) {
        users.filter { $0["id"].string == id }.first
    }

    return content["cars"].arrayValue.map {
        Car($0, findUser($0["user_id"].string))
    }
}
```

That’s a naive implementation that I just typed out, totally untested. You’d have to get it working, and figure out how you want to handle missing users (e.g. throw an error) etc.
