### ISSUE TITLE
Deprecation Swift 3

### ISSUE THREAD

**Issue by nissaba** [bustoutsolutions/siesta#53]
I used Carthage to build Siesta and the complier got me the following warnings. 

Checkouts/siesta/Source/Support/GCD+Siesta.swift:22:59: warning: __FUNCTION__ is deprecated and will be removed in Swift 3, please use #function

Carthage/Checkouts/siesta/Source/Support/Collection+Siesta.swift:83:29: warning: passing 2 arguments to a callee as a single tuple value is deprecated

**Comment by pcantrell** [comment]
Holding off on Swift 3 changes until the release has stabilized a bit — especially around all the API renamings are done and dust has settled on the new named parameter defaults.

At that point, we’ll do a complete pass for Swift 3 deprecations and breakages. The deep changes will probably necessitate separate Swift 2/3 branches, but waiting to see where all the details of the release lands before deciding that.

**Comment by pcantrell** [comment]
Also, @nissaba: once Swift 3 _has_ stabilized a bit and we’re ready to cut a Swift 3 branch of Siesta, I would gladly welcome pull requests to fix these sorts of issues!
