### ISSUE TITLE
Replace Nocilla in specs

### ISSUE THREAD

**Issue by pcantrell** [bustoutsolutions/siesta#60]
Nocilla has internal race conditions, and appears to be ill-maintained or abandoned. It works well enough for now, but it’s not ideal. Let’s investigate another HTTP stubbing framework.

@onekiloparsec points out the venerable [OHHTTPStubs](https://github.com/AliSoftware/OHHTTPStubs). Would need to investigate whether it can do ad hoc stubbing in code instead of reading from files.

[Mockingjay](https://github.com/kylef/Mockingjay) looks interesting.

The ability to explicitly delay and then resume responses is essential for Siesta’s specs. Any alternative would need to have that.

**Comment by onekiloparsec** [comment]
Almost 4 years later. Awesome, and congratulations !

**Comment by pcantrell** [comment]
Thanks! Feels good! And more good things coming.
