### ISSUE TITLE
Conflict between EntityCache and PersistentCache in beta 7

### ISSUE THREAD

**Issue by Alex293** [bustoutsolutions/siesta#66]
Hi, I have a siesta compile error since beta 7. Compilator says it need more context because there is two candidates for EntityCache class (in EntityCache.swift and in PersistentCache). 

<img width="233" alt="screen shot 2016-06-24 at 18 18 10" src="https://cloud.githubusercontent.com/assets/5930273/16343563/0854dd20-3a38-11e6-85bf-d0042a47d119.png">

**Comment by pcantrell** [comment]
Oops: `PersistentCache.swift` shouldn’t be there at all. Looks like it got accidentally re-added during the big OS X PR merge, but the project still compiles locally & with Carthage because `PersistentCache.swift` isn’t in the Xcode project. Fixing.

**Comment by Alex293** [comment]
Ok that's what i thought when i saw that this was exactly the same content
