### ISSUE TITLE
Removing plist files in a command-line build / Jenkins

### ISSUE THREAD

**Issue by Jissay** [bustoutsolutions/siesta#69]
Hello, 

I'm currently using Siesta framework in an internal iOS framework (written in Swift). This framework is built and tested by our Jenkins server. Sometimes, Jenkins may have some trouble cleaning the Build folder.

I use the XCode plugin for Jenkins, it build then test the project. It seems to build it two times in a row (one for the default action "build" and another for my custom settings that tells him to "test" the project). 

After the second step, my build fails (each time - i do a manual xcodebuild clean before running into XCode plugin). Here is my output : 

```
Testing failed:
Failed to remove /Users/jenkins/Library/Developer/Xcode/DerivedData/AXCoreSwift-cejrqtokifrbcyaxysroapbfuahi/Build/Products/Release-iphoneos/Siesta/Siesta.framework/Info-iOS.plist: “Info-iOS.plist” couldn’t be removed.
Failed to remove /Users/jenkins/Library/Developer/Xcode/DerivedData/AXCoreSwift-cejrqtokifrbcyaxysroapbfuahi/Build/Products/Release-iphoneos/Siesta/Siesta.framework/Info-OSX.plist: “Info-OSX.plist” couldn’t be removed.

Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure
Linker command failed with exit code 1 (use -v to see invocation)
** TEST FAILED **
```

It might be caused by permissions issues or a mistake while setting up my Jenkins, but i also managed (rarely, so very difficult to reproduce) to get it while building from XCode.

FYI, i also use SwiftyJSON and a few UI pods, nothing about another networking library. 
I can provide as much informations as needed

**Comment by pcantrell** [comment]
Mystery to me. I've never encountered this.

One shot in the dark: try removing `Info-*.plist` from the Siesta Xcode project — not the files themselves, just the references in the project file. They’re included in Source/Support.

**Comment by Jissay** [comment]
Hi, sorry for the late answer (i was on vacation).

Siesta has been installed using Cocoapods, removing file references means thats i need to create a script or something like a post-install hook to do so in my Jenkins build. 

I will update this thread as i get deeper in solving this issue,
Thank you for your help

**Comment by Jissay** [comment]
I did found the trick !

This solution is actually working within Jenkins CI (using XCode plugin or not). The thing here is to use `xcodeproj` gem to access to Pods groups and files reference. `xcodeproj` must be installed on the running Mac before executing this script (use `sudo gem install xcodeproj` to do so).

I switch this issue to closed. 

Added this in my podfile's post_install hook : 

```
# Need to execute "sudo gem install xcodeproj" before executing this post_install hook
post_install do |installer|
    
    # Removing Info-OSX.plist and Info-iOS.plist to avoid crash while building
    # with Jenkins CI. After a fresh pod install, Siesta isn't able to delete properly
    # these files. See https://github.com/bustoutsolutions/siesta/issues/69
    installer.pods_project.pods.groups.each { |g|
        
        if g.name == "Siesta"
            puts "--- Found Siesta group"
            g.groups.each { |g2|
                
                if g2.name == "Core"
                    puts "--- Found Core group, Removing Info-OSX.plist and Info-iOS.plist"
                    g2.files.each { |f|
                        if f.name == "Info-OSX.plist" || f.name == "Info-iOS.plist"
                            puts "--- Removing files"
                            f.remove_from_project
                        end
                    }
                end
            }
    
        end
    }
    
    # Update valid architectures parameters
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ARCHS'] = '$(ARCHS_STANDARD_INCLUDING_64_BIT)'
        end
    end
    
end
```

**Comment by pcantrell** [comment]
You might want to report this to the Cocoapods and Jenkins teams. It sure sounds like the problem is on one of their ends.

**Comment by pcantrell** [comment]
Aha! Looks like you might be hitting this: https://github.com/CocoaPods/CocoaPods/issues/3638

…and if so, looks like a fix is in the Cocoapods pipeline.
