### ISSUE TITLE
Make an initializer for Service which takes a NSURL instead of a String

### ISSUE THREAD

**Issue by jordanpwood** [bustoutsolutions/siesta#74]
I store my base URL as a `NSURL`, and every time I call the `Service` initializer (which isn't often, but I keep _moving_ it), I have to cast it to a `String`.  Its a tiny quibble, but since its so easy to fix, I thought I'd mention it.

Keep up the great work Paul!

**Comment by pcantrell** [comment]
Good point, this would be a nice convenience.
