### ISSUE TITLE
Remove pls Info-iOS.plist and Info-macOS.plist references from xcodeproject

### ISSUE THREAD

**Issue by Satchitananda** [bustoutsolutions/siesta#78]
When using CocoaPods it will make app not to launch on device with error "application does not have valid signature"

**Comment by pcantrell** [comment]
Thanks for the heads up! Able to reproduce, and looks like making the podspec explicitly ignore the `Info*.plist` fixes the problem.

**Comment by pcantrell** [comment]
Just released `1.0-beta.8a`, which should fix this. Let me know if it doesn’t.
