### ISSUE TITLE
>= 1.0-beta.7 code signing issue with cocoapods

### ISSUE THREAD

**Issue by Reedyuk** [bustoutsolutions/siesta#82]
Hi,
I have just spent quite a few hours trying to resolve an issue where i was compiling my application and trying to run it on my device, when i was getting 

> This application does not have a valid signature

. So i delved into the device logs,

```
streaming_zip_conduit[214] <Warning>: __dispatch_source_read_socket_block_invoke:299: Failed to install application at file:///var/mobile/Media/PublicStaging/SomeApp.app_sparse.ipa/ : Error Domain=LaunchServicesError Code=0 "(null)" UserInfo={Error=ApplicationVerificationFailed, ErrorDetail=-402620391, ErrorDescription=Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.wIFBM1/extracted/Payload/SomeApp.app/Frameworks/Siesta.framework : 0xe8008019 (The application does not have a valid signature.)}
Jul 28 11:32:35 A-iPhone UserEventAgent[26] <Error>: [appinstallation] LaunchServices observer: Apps Failed be installed: (
	    "<LSApplicationProxy: 0x15d6b9740> com.SomeApp.SomeApp <(null) *Not found in database*>"
	)
```

I finally reverted back and cleaned to 1.0-beta.6 and all is fine.

**Comment by gcasar** [comment]
Hello, 

I also experienced this issue. A project clean fixed it for me.

**Comment by Reedyuk** [comment]
So, i have this happening on multiple machines, i have also done multiple cleans, removed derived data, restart machine, closed Xcode, changed provisioning profiles. 
All did not work, then i changed the library version back to .6 and it works, when i change it back to .7 or .8, then it fails.

**Comment by pcantrell** [comment]
This sounds suspiciously like #78. Have you tried the `1.0-beta.8a` patch, just released?

**Comment by Reedyuk** [comment]
Ah, there is an 8a? i was using 8. 
Let me try now

**Comment by Reedyuk** [comment]
Confirmed, 8a fixes the problem. Thanks

**Comment by pcantrell** [comment]
Hmm, I should really update the README, shouldn’t I?
