### ISSUE TITLE
How can I set expiration time to infinite

### ISSUE THREAD

**Issue by Nandiin** [bustoutsolutions/siesta#83]
My remote api changes very infrequently, so there is no need for update some cache very frequently. Is there an option to set the expiration time to default? Does `expirationTime = NSTimeInterval.infinity` work?

**Comment by pcantrell** [comment]
Setting `expirationTime` to infinity will prevent `loadIfNeeded()` from ever fetching new data if it already has data available. Feel free to reopen this issue if that doesn’t work for you.
