### ISSUE TITLE
Using one BASE URL of a "Service" with two bit different url's services

### ISSUE THREAD

**Issue by nikolay-dementiev** [bustoutsolutions/siesta#84]
I have a question about how to use the Siesta - an iOS REST Client Framework https://bustoutsolutions.github.io/siesta/.

_(I just started to learn this framework)_

Is it possible to use one BASE URL of a "Service" with two bit different services?

_Problem:_ I need to connect to multiple services located on a domain _"openweathermap.org"_ ,for example: "http: //**api.**openweathermap.org/..." or
"http: //**bulk.**openweathermap.org/..." or still somehow  "http: //**....**openweathermap.org/..."

So, Now I have address (BASE URL): "http://api.openweathermap.org"
Can  I change it using the ".resource().relative()" like this:  "http: //bulk.openweathermap.org" ?

I'd like to get something like this: 
let service = Service(baseURL: "**openweathermap.org**")

- _(In the first case)_ service.resource().relative("http://**api.**")
- _(In the second case)_ service.resource().relative("http://**bulk.**")

..or somehow differently

Thanks

**Comment by pcantrell** [comment]
`Service.baseURL` has one and only one purpose: it is the starting point for `Service.resource(_:)` (with the unlabeled arg).

Yes, you can cross host boundaries with `Resource.relative()`, exactly as you suggest. You can also open arbitrary URLs with `Service.resource(absoluteURL:)`. In fact, you can create a `Service` with no `baseURL`, and always use `resource(absoluteURL:)`. [The Service spec](https://github.com/bustoutsolutions/siesta/blob/1.0-beta.8/Tests/ServiceSpec.swift) will answer a lot of questions about the details.

**Comment by nikolay-dementiev** [comment]
Thank you
