### ISSUE TITLE
The application does not have a valid signature

### ISSUE THREAD

**Issue by roma86** [bustoutsolutions/siesta#88]
Hello. I spend about 5 hours to research this problem, and finally can confirm it depends on this library.

When my Podfile include line  ```pod 'Siesta/Alamofire', '>=1.0-beta.8a'``` i can not run app on device. Simulator works fine, but on device i got **The application does not have a valid signature**.

```
pod --version 
1.0.1

Mac OS 10.11.6 (15G31)
Xcode 7.3.1 (7D1014)
```

Currently working Podfile looks like

```
platform :ios, '8.0'

target 'PodsApp' do
  source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!

  pod 'Fabric'
  pod 'Crashlytics'
  # pod 'Siesta/Alamofire', '>=1.0-beta.8a'
  pod 'AlamofireImage', '~> 2.0'
  pod 'SVProgressHUD', '~> 2.0.3'
  pod 'GRDB.swift', '~> 0.77.0'
  pod 'SHSPhoneComponent', '~> 2.15'
  pod 'SwiftDate', '~> 3.0.8'
  pod 'SwiftyJSON', '~> 2.3.1'

end
```

Is there are way to fix this? 
Thanks.

**Comment by pcantrell** [comment]
Curious — this sounds exactly like #82, which beta 8a should have fixed.

Perhaps it’s somehow a problem with the Alamofire subspec. Would you mind checking whether you still get this error with just the core Siesta pod?

    pod 'Siesta', '>=1.0-beta.8a'

**Comment by roma86** [comment]
@pcantrell hello. Thank you for answer.
Issue still here

![screen](https://api.monosnap.com/rpc/file/download?id=h1WFRJaZuIm0OlMuenX2og5t1owHMK)

**Comment by pcantrell** [comment]
Looks like this is a bug in CocoaPods: https://github.com/CocoaPods/CocoaPods/issues/5718

Remove the `>=` and it should work:

    pod 'Siesta', '1.0-beta.8a'

Let me know if that fixes it for you, and I’ll update the README.

**Comment by roma86** [comment]
It works now, but i need to remove DerivedData for that.

@pcantrell i really appreciate your help. Thank you.
