### ISSUE TITLE
documentation fail

### ISSUE THREAD

**Issue by jordanpwood** [bustoutsolutions/siesta#92]
The documentation at: http://bustoutsolutions.github.io/siesta/api/Extensions/String.html#/s:FE6SiestaSS20configurationPatternFCS_7ServiceFCSo5NSURLSb

isn't displaying the full documentation located at: https://github.com/bustoutsolutions/siesta/blob/1.0-beta.8/Source/ConfigurationPatternConvertible.swift#L45

That's some tricky escaping!  😸

**Comment by pcantrell** [comment]
Jazzy bug!

**Comment by pcantrell** [comment]
Filed Jazzy bug here: https://github.com/realm/jazzy/issues/635
