### ISSUE TITLE
Plus sign not encoded as %2B

### ISSUE THREAD

**Issue by vvondra** [bustoutsolutions/siesta#96]
Alamofire had a similar discussion about this https://github.com/Alamofire/Alamofire/issues/497

Currently, when calling:
```swift
resource().withParam("foo", "bar+baz")
```
the resulting URL will contain `?foo=bar+baz`

In most API implementations, the `+` sign in the query parameter value is interpreted as a space.

Siesta [already converts spaces to `%20`](https://github.com/bustoutsolutions/siesta/blob/master/Tests/ResourcePathsSpec.swift#L154) so it should also convert spaces to `%2B`

**Comment by pcantrell** [comment]
Agreed, this is a bug.

It should also arguably convert spaces to `+`, although `%20`, while inefficient, is at least harmless.
