### ISSUE TITLE
Request Retry

### ISSUE THREAD

**Issue by jwardle** [bustoutsolutions/siesta#99]
Currently Siesta does not allow your to retry a request (created via load*() functions). You can only "retry" a standard Resource by calling load() or loadIfNeeded() which does not support RequestMethods other than GET, and loses all previously appended onSuccess / onFailure / onCompletion callbacks. If the developer wishes to retry a more complex request then they have to reconstruct from scratch. 

A function to allow a previously failed request to be recreated (maintaining RequestMethod & callbacks) or to be retried entirely would be useful to avoid duplication of request generation code in POST / PUT / etc. scenarios. Without this it makes it difficult to create robust utility classes to handle negative conditions.

**Comment by pcantrell** [comment]
Please take a look at #98. It may be what you’re looking for. That pull request is open for user experimentation and feedback, so let me know what you think!

**Comment by jwardle** [comment]
Initial view of #98 having integrated it into our project looks spot on - will report back with any feedback. Additionally, this approach appears to have resolved a gap we were also facing with the token renewal / request retry cycle which you example clearly proposes a resolution for given the new changes.

**Comment by pcantrell** [comment]
Awesome! Thanks, @jwardle. I was waiting for second party confirmation that #98 isn’t broken before merging it. If you’ve tried it and yellow smoke didn’t come pouring out the vents, then I’ll go ahead and merge it.

**Comment by pcantrell** [comment]
Closing this, but it’s new functionality in need of more eyes — so please send questions, bugs, and enhancement ideas early and often.
